<?php


/**
 * This class adds structure of 'client_service' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Tue Mar 29 20:17:55 2011
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class ClientServiceMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.ClientServiceMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(ClientServicePeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(ClientServicePeer::TABLE_NAME);
		$tMap->setPhpName('ClientService');
		$tMap->setClassname('ClientService');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addForeignKey('CLIENT_ID', 'ClientId', 'INTEGER', 'client', 'ID', false, null);

		$tMap->addForeignKey('EMPLOYEE_ID', 'EmployeeId', 'INTEGER', 'employee', 'ID', false, null);

		$tMap->addForeignKey('SERVICE_ID', 'ServiceId', 'INTEGER', 'service', 'ID', false, null);

		$tMap->addForeignKey('FREQUENCY_ID', 'FrequencyId', 'INTEGER', 'frequency', 'ID', false, null);

		$tMap->addColumn('START_DATE', 'StartDate', 'TIMESTAMP', false, null);

		$tMap->addColumn('END_DATE', 'EndDate', 'TIMESTAMP', false, null);

		$tMap->addColumn('CHANGE_DATE', 'ChangeDate', 'TIMESTAMP', false, null);

		$tMap->addColumn('NOTES', 'Notes', 'LONGVARCHAR', false, null);

		$tMap->addForeignKey('ICD9_ID', 'Icd9Id', 'INTEGER', 'icd9', 'ID', false, null);

		$tMap->addColumn('AUTHORIZATION', 'Authorization', 'VARCHAR', false, 255);

		$tMap->addColumn('PHYSICIANS_ORDER', 'PhysiciansOrder', 'BOOLEAN', false, null);

		$tMap->addForeignKey('OFFICE_ID', 'OfficeId', 'INTEGER', 'office', 'ID', false, null);

		$tMap->addColumn('WAITING_LIST', 'WaitingList', 'BOOLEAN', false, null);

		$tMap->addColumn('OBJECT_TYPE', 'ObjectType', 'VARCHAR', false, 255);

	} // doBuild()

} // ClientServiceMapBuilder
