<?php


/**
 * This class adds structure of 'note_entry' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Tue Mar 29 20:17:55 2011
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class NoteEntryMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.NoteEntryMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(NoteEntryPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(NoteEntryPeer::TABLE_NAME);
		$tMap->setPhpName('NoteEntry');
		$tMap->setClassname('NoteEntry');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addForeignKey('EMPLOYEE_ID', 'EmployeeId', 'INTEGER', 'employee', 'ID', false, null);

		$tMap->addForeignKey('CLIENT_ID', 'ClientId', 'INTEGER', 'client', 'ID', false, null);

		$tMap->addForeignKey('CLIENT_SERVICE_ID', 'ClientServiceId', 'INTEGER', 'client_service', 'ID', false, null);

		$tMap->addForeignKey('OFFICE_ID', 'OfficeId', 'INTEGER', 'office', 'ID', false, null);

		$tMap->addForeignKey('FREQUENCY_ID', 'FrequencyId', 'INTEGER', 'frequency', 'ID', false, null);

		$tMap->addColumn('SERVICE_DATE', 'ServiceDate', 'TIMESTAMP', false, null);

		$tMap->addColumn('TIME_IN', 'TimeIn', 'TIMESTAMP', false, null);

		$tMap->addColumn('TIME_OUT', 'TimeOut', 'TIMESTAMP', false, null);

		$tMap->addColumn('CPT_CODE', 'CptCode', 'VARCHAR', false, 255);

		$tMap->addColumn('UNITS', 'Units', 'VARCHAR', false, 25);

		$tMap->addColumn('ABSENT', 'Absent', 'INTEGER', false, null);

		$tMap->addColumn('COMMENTS', 'Comments', 'LONGVARCHAR', false, null);

		$tMap->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null);

		$tMap->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null);

	} // doBuild()

} // NoteEntryMapBuilder
