<?php

/**
 * Base static class for performing query and update operations on the 'client' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Tue Mar 29 20:17:55 2011
 *
 * @package    lib.model.om
 */
abstract class BaseClientPeer {

	/** the default database name for this class */
	const DATABASE_NAME = 'propel';

	/** the table name for this class */
	const TABLE_NAME = 'client';

	/** A class that can be returned by this peer. */
	const CLASS_DEFAULT = 'lib.model.Client';

	/** The total number of columns. */
	const NUM_COLUMNS = 29;

	/** The number of lazy-loaded columns. */
	const NUM_LAZY_LOAD_COLUMNS = 0;

	/** the column name for the ID field */
	const ID = 'client.ID';

	/** the column name for the FIRST_NAME field */
	const FIRST_NAME = 'client.FIRST_NAME';

	/** the column name for the LAST_NAME field */
	const LAST_NAME = 'client.LAST_NAME';

	/** the column name for the DOB field */
	const DOB = 'client.DOB';

	/** the column name for the PARENT_FIRST field */
	const PARENT_FIRST = 'client.PARENT_FIRST';

	/** the column name for the PARENT_LAST field */
	const PARENT_LAST = 'client.PARENT_LAST';

	/** the column name for the PARENT2_FIRST field */
	const PARENT2_FIRST = 'client.PARENT2_FIRST';

	/** the column name for the PARENT2_LAST field */
	const PARENT2_LAST = 'client.PARENT2_LAST';

	/** the column name for the ADDRESS field */
	const ADDRESS = 'client.ADDRESS';

	/** the column name for the ADDRESS_2 field */
	const ADDRESS_2 = 'client.ADDRESS_2';

	/** the column name for the CITY field */
	const CITY = 'client.CITY';

	/** the column name for the STATE field */
	const STATE = 'client.STATE';

	/** the column name for the ZIP field */
	const ZIP = 'client.ZIP';

	/** the column name for the COUNTY_ID field */
	const COUNTY_ID = 'client.COUNTY_ID';

	/** the column name for the DISTRICT_ID field */
	const DISTRICT_ID = 'client.DISTRICT_ID';

	/** the column name for the HOME_PHONE field */
	const HOME_PHONE = 'client.HOME_PHONE';

	/** the column name for the WORK_PHONE field */
	const WORK_PHONE = 'client.WORK_PHONE';

	/** the column name for the CELL_PHONE field */
	const CELL_PHONE = 'client.CELL_PHONE';

	/** the column name for the BLUE_CARD field */
	const BLUE_CARD = 'client.BLUE_CARD';

	/** the column name for the IMMUNIZATIONS field */
	const IMMUNIZATIONS = 'client.IMMUNIZATIONS';

	/** the column name for the WAITING_LIST field */
	const WAITING_LIST = 'client.WAITING_LIST';

	/** the column name for the IS_IEP field */
	const IS_IEP = 'client.IS_IEP';

	/** the column name for the PHYSICAL_EXP field */
	const PHYSICAL_EXP = 'client.PHYSICAL_EXP';

	/** the column name for the PEDIATRICIAN field */
	const PEDIATRICIAN = 'client.PEDIATRICIAN';

	/** the column name for the NOTES field */
	const NOTES = 'client.NOTES';

	/** the column name for the SERVICE_COORDINATOR_ID field */
	const SERVICE_COORDINATOR_ID = 'client.SERVICE_COORDINATOR_ID';

	/** the column name for the EXTERNAL_SERVICE field */
	const EXTERNAL_SERVICE = 'client.EXTERNAL_SERVICE';

	/** the column name for the CREATED_AT field */
	const CREATED_AT = 'client.CREATED_AT';

	/** the column name for the UPDATED_AT field */
	const UPDATED_AT = 'client.UPDATED_AT';

	/**
	 * An identiy map to hold any loaded instances of Client objects.
	 * This must be public so that other peer classes can access this when hydrating from JOIN
	 * queries.
	 * @var        array Client[]
	 */
	public static $instances = array();

	/**
	 * The MapBuilder instance for this peer.
	 * @var        MapBuilder
	 */
	private static $mapBuilder = null;

	/**
	 * holds an array of fieldnames
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[self::TYPE_PHPNAME][0] = 'Id'
	 */
	private static $fieldNames = array (
		BasePeer::TYPE_PHPNAME => array ('Id', 'FirstName', 'LastName', 'Dob', 'ParentFirst', 'ParentLast', 'Parent2First', 'Parent2Last', 'Address', 'Address2', 'City', 'State', 'Zip', 'CountyId', 'DistrictId', 'HomePhone', 'WorkPhone', 'CellPhone', 'BlueCard', 'Immunizations', 'WaitingList', 'IsIep', 'PhysicalExp', 'Pediatrician', 'Notes', 'ServiceCoordinatorId', 'ExternalService', 'CreatedAt', 'UpdatedAt', ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id', 'firstName', 'lastName', 'dob', 'parentFirst', 'parentLast', 'parent2First', 'parent2Last', 'address', 'address2', 'city', 'state', 'zip', 'countyId', 'districtId', 'homePhone', 'workPhone', 'cellPhone', 'blueCard', 'immunizations', 'waitingList', 'isIep', 'physicalExp', 'pediatrician', 'notes', 'serviceCoordinatorId', 'externalService', 'createdAt', 'updatedAt', ),
		BasePeer::TYPE_COLNAME => array (self::ID, self::FIRST_NAME, self::LAST_NAME, self::DOB, self::PARENT_FIRST, self::PARENT_LAST, self::PARENT2_FIRST, self::PARENT2_LAST, self::ADDRESS, self::ADDRESS_2, self::CITY, self::STATE, self::ZIP, self::COUNTY_ID, self::DISTRICT_ID, self::HOME_PHONE, self::WORK_PHONE, self::CELL_PHONE, self::BLUE_CARD, self::IMMUNIZATIONS, self::WAITING_LIST, self::IS_IEP, self::PHYSICAL_EXP, self::PEDIATRICIAN, self::NOTES, self::SERVICE_COORDINATOR_ID, self::EXTERNAL_SERVICE, self::CREATED_AT, self::UPDATED_AT, ),
		BasePeer::TYPE_FIELDNAME => array ('id', 'first_name', 'last_name', 'dob', 'parent_first', 'parent_last', 'parent2_first', 'parent2_last', 'address', 'address_2', 'city', 'state', 'zip', 'county_id', 'district_id', 'home_phone', 'work_phone', 'cell_phone', 'blue_card', 'immunizations', 'waiting_list', 'is_iep', 'physical_exp', 'pediatrician', 'notes', 'service_coordinator_id', 'external_service', 'created_at', 'updated_at', ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, )
	);

	/**
	 * holds an array of keys for quick access to the fieldnames array
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
	 */
	private static $fieldKeys = array (
		BasePeer::TYPE_PHPNAME => array ('Id' => 0, 'FirstName' => 1, 'LastName' => 2, 'Dob' => 3, 'ParentFirst' => 4, 'ParentLast' => 5, 'Parent2First' => 6, 'Parent2Last' => 7, 'Address' => 8, 'Address2' => 9, 'City' => 10, 'State' => 11, 'Zip' => 12, 'CountyId' => 13, 'DistrictId' => 14, 'HomePhone' => 15, 'WorkPhone' => 16, 'CellPhone' => 17, 'BlueCard' => 18, 'Immunizations' => 19, 'WaitingList' => 20, 'IsIep' => 21, 'PhysicalExp' => 22, 'Pediatrician' => 23, 'Notes' => 24, 'ServiceCoordinatorId' => 25, 'ExternalService' => 26, 'CreatedAt' => 27, 'UpdatedAt' => 28, ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id' => 0, 'firstName' => 1, 'lastName' => 2, 'dob' => 3, 'parentFirst' => 4, 'parentLast' => 5, 'parent2First' => 6, 'parent2Last' => 7, 'address' => 8, 'address2' => 9, 'city' => 10, 'state' => 11, 'zip' => 12, 'countyId' => 13, 'districtId' => 14, 'homePhone' => 15, 'workPhone' => 16, 'cellPhone' => 17, 'blueCard' => 18, 'immunizations' => 19, 'waitingList' => 20, 'isIep' => 21, 'physicalExp' => 22, 'pediatrician' => 23, 'notes' => 24, 'serviceCoordinatorId' => 25, 'externalService' => 26, 'createdAt' => 27, 'updatedAt' => 28, ),
		BasePeer::TYPE_COLNAME => array (self::ID => 0, self::FIRST_NAME => 1, self::LAST_NAME => 2, self::DOB => 3, self::PARENT_FIRST => 4, self::PARENT_LAST => 5, self::PARENT2_FIRST => 6, self::PARENT2_LAST => 7, self::ADDRESS => 8, self::ADDRESS_2 => 9, self::CITY => 10, self::STATE => 11, self::ZIP => 12, self::COUNTY_ID => 13, self::DISTRICT_ID => 14, self::HOME_PHONE => 15, self::WORK_PHONE => 16, self::CELL_PHONE => 17, self::BLUE_CARD => 18, self::IMMUNIZATIONS => 19, self::WAITING_LIST => 20, self::IS_IEP => 21, self::PHYSICAL_EXP => 22, self::PEDIATRICIAN => 23, self::NOTES => 24, self::SERVICE_COORDINATOR_ID => 25, self::EXTERNAL_SERVICE => 26, self::CREATED_AT => 27, self::UPDATED_AT => 28, ),
		BasePeer::TYPE_FIELDNAME => array ('id' => 0, 'first_name' => 1, 'last_name' => 2, 'dob' => 3, 'parent_first' => 4, 'parent_last' => 5, 'parent2_first' => 6, 'parent2_last' => 7, 'address' => 8, 'address_2' => 9, 'city' => 10, 'state' => 11, 'zip' => 12, 'county_id' => 13, 'district_id' => 14, 'home_phone' => 15, 'work_phone' => 16, 'cell_phone' => 17, 'blue_card' => 18, 'immunizations' => 19, 'waiting_list' => 20, 'is_iep' => 21, 'physical_exp' => 22, 'pediatrician' => 23, 'notes' => 24, 'service_coordinator_id' => 25, 'external_service' => 26, 'created_at' => 27, 'updated_at' => 28, ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, )
	);

	/**
	 * Get a (singleton) instance of the MapBuilder for this peer class.
	 * @return     MapBuilder The map builder for this peer
	 */
	public static function getMapBuilder()
	{
		if (self::$mapBuilder === null) {
			self::$mapBuilder = new ClientMapBuilder();
		}
		return self::$mapBuilder;
	}
	/**
	 * Translates a fieldname to another type
	 *
	 * @param      string $name field name
	 * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @param      string $toType   One of the class type constants
	 * @return     string translated name of the field.
	 * @throws     PropelException - if the specified name could not be found in the fieldname mappings.
	 */
	static public function translateFieldName($name, $fromType, $toType)
	{
		$toNames = self::getFieldNames($toType);
		$key = isset(self::$fieldKeys[$fromType][$name]) ? self::$fieldKeys[$fromType][$name] : null;
		if ($key === null) {
			throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(self::$fieldKeys[$fromType], true));
		}
		return $toNames[$key];
	}

	/**
	 * Returns an array of field names.
	 *
	 * @param      string $type The type of fieldnames to return:
	 *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     array A list of field names
	 */

	static public function getFieldNames($type = BasePeer::TYPE_PHPNAME)
	{
		if (!array_key_exists($type, self::$fieldNames)) {
			throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
		}
		return self::$fieldNames[$type];
	}

	/**
	 * Convenience method which changes table.column to alias.column.
	 *
	 * Using this method you can maintain SQL abstraction while using column aliases.
	 * <code>
	 *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
	 *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
	 * </code>
	 * @param      string $alias The alias for the current table.
	 * @param      string $column The column name for current table. (i.e. ClientPeer::COLUMN_NAME).
	 * @return     string
	 */
	public static function alias($alias, $column)
	{
		return str_replace(ClientPeer::TABLE_NAME.'.', $alias.'.', $column);
	}

	/**
	 * Add all the columns needed to create a new object.
	 *
	 * Note: any columns that were marked with lazyLoad="true" in the
	 * XML schema will not be added to the select list and only loaded
	 * on demand.
	 *
	 * @param      criteria object containing the columns to add.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function addSelectColumns(Criteria $criteria)
	{

		$criteria->addSelectColumn(ClientPeer::ID);

		$criteria->addSelectColumn(ClientPeer::FIRST_NAME);

		$criteria->addSelectColumn(ClientPeer::LAST_NAME);

		$criteria->addSelectColumn(ClientPeer::DOB);

		$criteria->addSelectColumn(ClientPeer::PARENT_FIRST);

		$criteria->addSelectColumn(ClientPeer::PARENT_LAST);

		$criteria->addSelectColumn(ClientPeer::PARENT2_FIRST);

		$criteria->addSelectColumn(ClientPeer::PARENT2_LAST);

		$criteria->addSelectColumn(ClientPeer::ADDRESS);

		$criteria->addSelectColumn(ClientPeer::ADDRESS_2);

		$criteria->addSelectColumn(ClientPeer::CITY);

		$criteria->addSelectColumn(ClientPeer::STATE);

		$criteria->addSelectColumn(ClientPeer::ZIP);

		$criteria->addSelectColumn(ClientPeer::COUNTY_ID);

		$criteria->addSelectColumn(ClientPeer::DISTRICT_ID);

		$criteria->addSelectColumn(ClientPeer::HOME_PHONE);

		$criteria->addSelectColumn(ClientPeer::WORK_PHONE);

		$criteria->addSelectColumn(ClientPeer::CELL_PHONE);

		$criteria->addSelectColumn(ClientPeer::BLUE_CARD);

		$criteria->addSelectColumn(ClientPeer::IMMUNIZATIONS);

		$criteria->addSelectColumn(ClientPeer::WAITING_LIST);

		$criteria->addSelectColumn(ClientPeer::IS_IEP);

		$criteria->addSelectColumn(ClientPeer::PHYSICAL_EXP);

		$criteria->addSelectColumn(ClientPeer::PEDIATRICIAN);

		$criteria->addSelectColumn(ClientPeer::NOTES);

		$criteria->addSelectColumn(ClientPeer::SERVICE_COORDINATOR_ID);

		$criteria->addSelectColumn(ClientPeer::EXTERNAL_SERVICE);

		$criteria->addSelectColumn(ClientPeer::CREATED_AT);

		$criteria->addSelectColumn(ClientPeer::UPDATED_AT);

	}

	/**
	 * Returns the number of rows matching criteria.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @return     int Number of matching rows.
	 */
	public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
	{
		// we may modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(ClientPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			ClientPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		$criteria->setDbName(self::DATABASE_NAME); // Set the correct dbName

		if ($con === null) {
			$con = Propel::getConnection(ClientPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}


    foreach (sfMixer::getCallables('BaseClientPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseClientPeer', $criteria, $con);
    }


		// BasePeer returns a PDOStatement
		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}
	/**
	 * Method to select one object from the DB.
	 *
	 * @param      Criteria $criteria object used to create the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     Client
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
	{
		$critcopy = clone $criteria;
		$critcopy->setLimit(1);
		$objects = ClientPeer::doSelect($critcopy, $con);
		if ($objects) {
			return $objects[0];
		}
		return null;
	}
	/**
	 * Method to do selects.
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     array Array of selected Objects
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelect(Criteria $criteria, PropelPDO $con = null)
	{
		return ClientPeer::populateObjects(ClientPeer::doSelectStmt($criteria, $con));
	}
	/**
	 * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
	 *
	 * Use this method directly if you want to work with an executed statement durirectly (for example
	 * to perform your own object hydration).
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con The connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     PDOStatement The executed PDOStatement object.
	 * @see        BasePeer::doSelect()
	 */
	public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseClientPeer:doSelectStmt:doSelectStmt') as $callable)
    {
      call_user_func($callable, 'BaseClientPeer', $criteria, $con);
    }


		if ($con === null) {
			$con = Propel::getConnection(ClientPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		if (!$criteria->hasSelectClause()) {
			$criteria = clone $criteria;
			ClientPeer::addSelectColumns($criteria);
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		// BasePeer returns a PDOStatement
		return BasePeer::doSelect($criteria, $con);
	}
	/**
	 * Adds an object to the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doSelect*()
	 * methods in your stub classes -- you may need to explicitly add objects
	 * to the cache in order to ensure that the same objects are always returned by doSelect*()
	 * and retrieveByPK*() calls.
	 *
	 * @param      Client $value A Client object.
	 * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
	 */
	public static function addInstanceToPool(Client $obj, $key = null)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if ($key === null) {
				$key = (string) $obj->getId();
			} // if key === null
			self::$instances[$key] = $obj;
		}
	}

	/**
	 * Removes an object from the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doDelete
	 * methods in your stub classes -- you may need to explicitly remove objects
	 * from the cache in order to prevent returning objects that no longer exist.
	 *
	 * @param      mixed $value A Client object or a primary key value.
	 */
	public static function removeInstanceFromPool($value)
	{
		if (Propel::isInstancePoolingEnabled() && $value !== null) {
			if (is_object($value) && $value instanceof Client) {
				$key = (string) $value->getId();
			} elseif (is_scalar($value)) {
				// assume we've been passed a primary key
				$key = (string) $value;
			} else {
				$e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or Client object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
				throw $e;
			}

			unset(self::$instances[$key]);
		}
	} // removeInstanceFromPool()

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
	 * @return     Client Found object or NULL if 1) no instance exists for specified key or 2) instance pooling has been disabled.
	 * @see        getPrimaryKeyHash()
	 */
	public static function getInstanceFromPool($key)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if (isset(self::$instances[$key])) {
				return self::$instances[$key];
			}
		}
		return null; // just to be explicit
	}
	
	/**
	 * Clear the instance pool.
	 *
	 * @return     void
	 */
	public static function clearInstancePool()
	{
		self::$instances = array();
	}
	
	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     string A string version of PK or NULL if the components of primary key in result array are all null.
	 */
	public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
	{
		// If the PK cannot be derived from the row, return NULL.
		if ($row[$startcol + 0] === null) {
			return null;
		}
		return (string) $row[$startcol + 0];
	}

	/**
	 * The returned array will contain objects of the default type or
	 * objects that inherit from the default.
	 *
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function populateObjects(PDOStatement $stmt)
	{
		$results = array();
	
		// set the class once to avoid overhead in the loop
		$cls = ClientPeer::getOMClass();
		$cls = substr('.'.$cls, strrpos('.'.$cls, '.') + 1);
		// populate the object(s)
		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key = ClientPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj = ClientPeer::getInstanceFromPool($key))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj->hydrate($row, 0, true); // rehydrate
				$results[] = $obj;
			} else {
		
				$obj = new $cls();
				$obj->hydrate($row);
				$results[] = $obj;
				ClientPeer::addInstanceToPool($obj, $key);
			} // if key exists
		}
		$stmt->closeCursor();
		return $results;
	}

	/**
	 * Returns the number of rows matching criteria, joining the related County table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinCounty(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(ClientPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			ClientPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(ClientPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(ClientPeer::COUNTY_ID,), array(CountyPeer::ID,), $join_behavior);


    foreach (sfMixer::getCallables('BaseClientPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseClientPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related District table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinDistrict(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(ClientPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			ClientPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(ClientPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(ClientPeer::DISTRICT_ID,), array(DistrictPeer::ID,), $join_behavior);


    foreach (sfMixer::getCallables('BaseClientPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseClientPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related ServiceCoordinator table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinServiceCoordinator(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(ClientPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			ClientPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(ClientPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(ClientPeer::SERVICE_COORDINATOR_ID,), array(ServiceCoordinatorPeer::ID,), $join_behavior);


    foreach (sfMixer::getCallables('BaseClientPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseClientPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Selects a collection of Client objects pre-filled with their County objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Client objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinCounty(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{

    foreach (sfMixer::getCallables('BaseClientPeer:doSelectJoin:doSelectJoin') as $callable)
    {
      call_user_func($callable, 'BaseClientPeer', $c, $con);
    }


		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		ClientPeer::addSelectColumns($c);
		$startcol = (ClientPeer::NUM_COLUMNS - ClientPeer::NUM_LAZY_LOAD_COLUMNS);
		CountyPeer::addSelectColumns($c);

		$c->addJoin(array(ClientPeer::COUNTY_ID,), array(CountyPeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = ClientPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = ClientPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = ClientPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				ClientPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = CountyPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = CountyPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = CountyPeer::getOMClass();

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					CountyPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (Client) to $obj2 (County)
				$obj2->addClient($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Client objects pre-filled with their District objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Client objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinDistrict(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		ClientPeer::addSelectColumns($c);
		$startcol = (ClientPeer::NUM_COLUMNS - ClientPeer::NUM_LAZY_LOAD_COLUMNS);
		DistrictPeer::addSelectColumns($c);

		$c->addJoin(array(ClientPeer::DISTRICT_ID,), array(DistrictPeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = ClientPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = ClientPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = ClientPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				ClientPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = DistrictPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = DistrictPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = DistrictPeer::getOMClass();

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					DistrictPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (Client) to $obj2 (District)
				$obj2->addClient($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Client objects pre-filled with their ServiceCoordinator objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Client objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinServiceCoordinator(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		ClientPeer::addSelectColumns($c);
		$startcol = (ClientPeer::NUM_COLUMNS - ClientPeer::NUM_LAZY_LOAD_COLUMNS);
		ServiceCoordinatorPeer::addSelectColumns($c);

		$c->addJoin(array(ClientPeer::SERVICE_COORDINATOR_ID,), array(ServiceCoordinatorPeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = ClientPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = ClientPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = ClientPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				ClientPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = ServiceCoordinatorPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = ServiceCoordinatorPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = ServiceCoordinatorPeer::getOMClass();

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					ServiceCoordinatorPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (Client) to $obj2 (ServiceCoordinator)
				$obj2->addClient($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Returns the number of rows matching criteria, joining all related tables
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAll(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(ClientPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			ClientPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(ClientPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(ClientPeer::COUNTY_ID,), array(CountyPeer::ID,), $join_behavior);
		$criteria->addJoin(array(ClientPeer::DISTRICT_ID,), array(DistrictPeer::ID,), $join_behavior);
		$criteria->addJoin(array(ClientPeer::SERVICE_COORDINATOR_ID,), array(ServiceCoordinatorPeer::ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseClientPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseClientPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}

	/**
	 * Selects a collection of Client objects pre-filled with all related objects.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Client objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAll(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{

    foreach (sfMixer::getCallables('BaseClientPeer:doSelectJoinAll:doSelectJoinAll') as $callable)
    {
      call_user_func($callable, 'BaseClientPeer', $c, $con);
    }


		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		ClientPeer::addSelectColumns($c);
		$startcol2 = (ClientPeer::NUM_COLUMNS - ClientPeer::NUM_LAZY_LOAD_COLUMNS);

		CountyPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (CountyPeer::NUM_COLUMNS - CountyPeer::NUM_LAZY_LOAD_COLUMNS);

		DistrictPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (DistrictPeer::NUM_COLUMNS - DistrictPeer::NUM_LAZY_LOAD_COLUMNS);

		ServiceCoordinatorPeer::addSelectColumns($c);
		$startcol5 = $startcol4 + (ServiceCoordinatorPeer::NUM_COLUMNS - ServiceCoordinatorPeer::NUM_LAZY_LOAD_COLUMNS);

		$c->addJoin(array(ClientPeer::COUNTY_ID,), array(CountyPeer::ID,), $join_behavior);
		$c->addJoin(array(ClientPeer::DISTRICT_ID,), array(DistrictPeer::ID,), $join_behavior);
		$c->addJoin(array(ClientPeer::SERVICE_COORDINATOR_ID,), array(ServiceCoordinatorPeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = ClientPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = ClientPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = ClientPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				ClientPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

			// Add objects for joined County rows

			$key2 = CountyPeer::getPrimaryKeyHashFromRow($row, $startcol2);
			if ($key2 !== null) {
				$obj2 = CountyPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = CountyPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					CountyPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 loaded

				// Add the $obj1 (Client) to the collection in $obj2 (County)
				$obj2->addClient($obj1);
			} // if joined row not null

			// Add objects for joined District rows

			$key3 = DistrictPeer::getPrimaryKeyHashFromRow($row, $startcol3);
			if ($key3 !== null) {
				$obj3 = DistrictPeer::getInstanceFromPool($key3);
				if (!$obj3) {

					$omClass = DistrictPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					DistrictPeer::addInstanceToPool($obj3, $key3);
				} // if obj3 loaded

				// Add the $obj1 (Client) to the collection in $obj3 (District)
				$obj3->addClient($obj1);
			} // if joined row not null

			// Add objects for joined ServiceCoordinator rows

			$key4 = ServiceCoordinatorPeer::getPrimaryKeyHashFromRow($row, $startcol4);
			if ($key4 !== null) {
				$obj4 = ServiceCoordinatorPeer::getInstanceFromPool($key4);
				if (!$obj4) {

					$omClass = ServiceCoordinatorPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					ServiceCoordinatorPeer::addInstanceToPool($obj4, $key4);
				} // if obj4 loaded

				// Add the $obj1 (Client) to the collection in $obj4 (ServiceCoordinator)
				$obj4->addClient($obj1);
			} // if joined row not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related County table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptCounty(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			ClientPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(ClientPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(ClientPeer::DISTRICT_ID,), array(DistrictPeer::ID,), $join_behavior);
				$criteria->addJoin(array(ClientPeer::SERVICE_COORDINATOR_ID,), array(ServiceCoordinatorPeer::ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseClientPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseClientPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related District table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptDistrict(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			ClientPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(ClientPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(ClientPeer::COUNTY_ID,), array(CountyPeer::ID,), $join_behavior);
				$criteria->addJoin(array(ClientPeer::SERVICE_COORDINATOR_ID,), array(ServiceCoordinatorPeer::ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseClientPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseClientPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related ServiceCoordinator table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptServiceCoordinator(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			ClientPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(ClientPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(ClientPeer::COUNTY_ID,), array(CountyPeer::ID,), $join_behavior);
				$criteria->addJoin(array(ClientPeer::DISTRICT_ID,), array(DistrictPeer::ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseClientPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseClientPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Selects a collection of Client objects pre-filled with all related objects except County.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Client objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptCounty(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{

    foreach (sfMixer::getCallables('BaseClientPeer:doSelectJoinAllExcept:doSelectJoinAllExcept') as $callable)
    {
      call_user_func($callable, 'BaseClientPeer', $c, $con);
    }


		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		ClientPeer::addSelectColumns($c);
		$startcol2 = (ClientPeer::NUM_COLUMNS - ClientPeer::NUM_LAZY_LOAD_COLUMNS);

		DistrictPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (DistrictPeer::NUM_COLUMNS - DistrictPeer::NUM_LAZY_LOAD_COLUMNS);

		ServiceCoordinatorPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (ServiceCoordinatorPeer::NUM_COLUMNS - ServiceCoordinatorPeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(ClientPeer::DISTRICT_ID,), array(DistrictPeer::ID,), $join_behavior);
				$c->addJoin(array(ClientPeer::SERVICE_COORDINATOR_ID,), array(ServiceCoordinatorPeer::ID,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = ClientPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = ClientPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = ClientPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				ClientPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined District rows

				$key2 = DistrictPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = DistrictPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = DistrictPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					DistrictPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (Client) to the collection in $obj2 (District)
				$obj2->addClient($obj1);

			} // if joined row is not null

				// Add objects for joined ServiceCoordinator rows

				$key3 = ServiceCoordinatorPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = ServiceCoordinatorPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$omClass = ServiceCoordinatorPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					ServiceCoordinatorPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (Client) to the collection in $obj3 (ServiceCoordinator)
				$obj3->addClient($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Client objects pre-filled with all related objects except District.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Client objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptDistrict(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		ClientPeer::addSelectColumns($c);
		$startcol2 = (ClientPeer::NUM_COLUMNS - ClientPeer::NUM_LAZY_LOAD_COLUMNS);

		CountyPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (CountyPeer::NUM_COLUMNS - CountyPeer::NUM_LAZY_LOAD_COLUMNS);

		ServiceCoordinatorPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (ServiceCoordinatorPeer::NUM_COLUMNS - ServiceCoordinatorPeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(ClientPeer::COUNTY_ID,), array(CountyPeer::ID,), $join_behavior);
				$c->addJoin(array(ClientPeer::SERVICE_COORDINATOR_ID,), array(ServiceCoordinatorPeer::ID,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = ClientPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = ClientPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = ClientPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				ClientPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined County rows

				$key2 = CountyPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = CountyPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = CountyPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					CountyPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (Client) to the collection in $obj2 (County)
				$obj2->addClient($obj1);

			} // if joined row is not null

				// Add objects for joined ServiceCoordinator rows

				$key3 = ServiceCoordinatorPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = ServiceCoordinatorPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$omClass = ServiceCoordinatorPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					ServiceCoordinatorPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (Client) to the collection in $obj3 (ServiceCoordinator)
				$obj3->addClient($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Client objects pre-filled with all related objects except ServiceCoordinator.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Client objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptServiceCoordinator(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		ClientPeer::addSelectColumns($c);
		$startcol2 = (ClientPeer::NUM_COLUMNS - ClientPeer::NUM_LAZY_LOAD_COLUMNS);

		CountyPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (CountyPeer::NUM_COLUMNS - CountyPeer::NUM_LAZY_LOAD_COLUMNS);

		DistrictPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (DistrictPeer::NUM_COLUMNS - DistrictPeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(ClientPeer::COUNTY_ID,), array(CountyPeer::ID,), $join_behavior);
				$c->addJoin(array(ClientPeer::DISTRICT_ID,), array(DistrictPeer::ID,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = ClientPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = ClientPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = ClientPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				ClientPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined County rows

				$key2 = CountyPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = CountyPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = CountyPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					CountyPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (Client) to the collection in $obj2 (County)
				$obj2->addClient($obj1);

			} // if joined row is not null

				// Add objects for joined District rows

				$key3 = DistrictPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = DistrictPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$omClass = DistrictPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					DistrictPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (Client) to the collection in $obj3 (District)
				$obj3->addClient($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


  static public function getUniqueColumnNames()
  {
    return array();
  }
	/**
	 * Returns the TableMap related to this peer.
	 * This method is not needed for general use but a specific application could have a need.
	 * @return     TableMap
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function getTableMap()
	{
		return Propel::getDatabaseMap(self::DATABASE_NAME)->getTable(self::TABLE_NAME);
	}

	/**
	 * The class that the Peer will make instances of.
	 *
	 * This uses a dot-path notation which is tranalted into a path
	 * relative to a location on the PHP include_path.
	 * (e.g. path.to.MyClass -> 'path/to/MyClass.php')
	 *
	 * @return     string path.to.ClassName
	 */
	public static function getOMClass()
	{
		return ClientPeer::CLASS_DEFAULT;
	}

	/**
	 * Method perform an INSERT on the database, given a Client or Criteria object.
	 *
	 * @param      mixed $values Criteria or Client object containing data that is used to create the INSERT statement.
	 * @param      PropelPDO $con the PropelPDO connection to use
	 * @return     mixed The new primary key.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doInsert($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseClientPeer:doInsert:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseClientPeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(ClientPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity
		} else {
			$criteria = $values->buildCriteria(); // build Criteria from Client object
		}

		if ($criteria->containsKey(ClientPeer::ID) && $criteria->keyContainsValue(ClientPeer::ID) ) {
			throw new PropelException('Cannot insert a value for auto-increment primary key ('.ClientPeer::ID.')');
		}


		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		try {
			// use transaction because $criteria could contain info
			// for more than one table (I guess, conceivably)
			$con->beginTransaction();
			$pk = BasePeer::doInsert($criteria, $con);
			$con->commit();
		} catch(PropelException $e) {
			$con->rollBack();
			throw $e;
		}

		
    foreach (sfMixer::getCallables('BaseClientPeer:doInsert:post') as $callable)
    {
      call_user_func($callable, 'BaseClientPeer', $values, $con, $pk);
    }

    return $pk;
	}

	/**
	 * Method perform an UPDATE on the database, given a Client or Criteria object.
	 *
	 * @param      mixed $values Criteria or Client object containing data that is used to create the UPDATE statement.
	 * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doUpdate($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseClientPeer:doUpdate:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseClientPeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(ClientPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$selectCriteria = new Criteria(self::DATABASE_NAME);

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity

			$comparison = $criteria->getComparison(ClientPeer::ID);
			$selectCriteria->add(ClientPeer::ID, $criteria->remove(ClientPeer::ID), $comparison);

		} else { // $values is Client object
			$criteria = $values->buildCriteria(); // gets full criteria
			$selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
		}

		// set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$ret = BasePeer::doUpdate($selectCriteria, $criteria, $con);
	

    foreach (sfMixer::getCallables('BaseClientPeer:doUpdate:post') as $callable)
    {
      call_user_func($callable, 'BaseClientPeer', $values, $con, $ret);
    }

    return $ret;
  }

	/**
	 * Method to DELETE all rows from the client table.
	 *
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	public static function doDeleteAll($con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(ClientPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		$affectedRows = 0; // initialize var to track total num of affected rows
		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += ClientPeer::doOnDeleteCascade(new Criteria(ClientPeer::DATABASE_NAME), $con);
			ClientPeer::doOnDeleteSetNull(new Criteria(ClientPeer::DATABASE_NAME), $con);
			$affectedRows += BasePeer::doDeleteAll(ClientPeer::TABLE_NAME, $con);
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Method perform a DELETE on the database, given a Client or Criteria object OR a primary key value.
	 *
	 * @param      mixed $values Criteria or Client object or primary key or array of primary keys
	 *              which is used to create the DELETE statement
	 * @param      PropelPDO $con the connection to use
	 * @return     int 	The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
	 *				if supported by native driver or if emulated using Propel.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	 public static function doDelete($values, PropelPDO $con = null)
	 {
		if ($con === null) {
			$con = Propel::getConnection(ClientPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			// invalidate the cache for all objects of this type, since we have no
			// way of knowing (without running a query) what objects should be invalidated
			// from the cache based on this Criteria.
			ClientPeer::clearInstancePool();

			// rename for clarity
			$criteria = clone $values;
		} elseif ($values instanceof Client) {
			// invalidate the cache for this single object
			ClientPeer::removeInstanceFromPool($values);
			// create criteria based on pk values
			$criteria = $values->buildPkeyCriteria();
		} else {
			// it must be the primary key



			$criteria = new Criteria(self::DATABASE_NAME);
			$criteria->add(ClientPeer::ID, (array) $values, Criteria::IN);

			foreach ((array) $values as $singleval) {
				// we can invalidate the cache for this single object
				ClientPeer::removeInstanceFromPool($singleval);
			}
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$affectedRows = 0; // initialize var to track total num of affected rows

		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += ClientPeer::doOnDeleteCascade($criteria, $con);
			ClientPeer::doOnDeleteSetNull($criteria, $con);
			
				// Because this db requires some delete cascade/set null emulation, we have to
				// clear the cached instance *after* the emulation has happened (since
				// instances get re-added by the select statement contained therein).
				if ($values instanceof Criteria) {
					ClientPeer::clearInstancePool();
				} else { // it's a PK or object
					ClientPeer::removeInstanceFromPool($values);
				}
			
			$affectedRows += BasePeer::doDelete($criteria, $con);

			// invalidate objects in ClientServicePeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
			ClientServicePeer::clearInstancePool();

			// invalidate objects in NoteEntryPeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
			NoteEntryPeer::clearInstancePool();

			// invalidate objects in NoteEntryKidsPeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
			NoteEntryKidsPeer::clearInstancePool();

			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * This is a method for emulating ON DELETE CASCADE for DBs that don't support this
	 * feature (like MySQL or SQLite).
	 *
	 * This method is not very speedy because it must perform a query first to get
	 * the implicated records and then perform the deletes by calling those Peer classes.
	 *
	 * This method should be used within a transaction if possible.
	 *
	 * @param      Criteria $criteria
	 * @param      PropelPDO $con
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	protected static function doOnDeleteCascade(Criteria $criteria, PropelPDO $con)
	{
		// initialize var to track total num of affected rows
		$affectedRows = 0;

		// first find the objects that are implicated by the $criteria
		$objects = ClientPeer::doSelect($criteria, $con);
		foreach ($objects as $obj) {


			// delete related NoteEntryKids objects
			$c = new Criteria(NoteEntryKidsPeer::DATABASE_NAME);
			
			$c->add(NoteEntryKidsPeer::CLIENT_ID, $obj->getId());
			$affectedRows += NoteEntryKidsPeer::doDelete($c, $con);
		}
		return $affectedRows;
	}

	/**
	 * This is a method for emulating ON DELETE SET NULL DBs that don't support this
	 * feature (like MySQL or SQLite).
	 *
	 * This method is not very speedy because it must perform a query first to get
	 * the implicated records and then perform the deletes by calling those Peer classes.
	 *
	 * This method should be used within a transaction if possible.
	 *
	 * @param      Criteria $criteria
	 * @param      PropelPDO $con
	 * @return     void
	 */
	protected static function doOnDeleteSetNull(Criteria $criteria, PropelPDO $con)
	{

		// first find the objects that are implicated by the $criteria
		$objects = ClientPeer::doSelect($criteria, $con);
		foreach ($objects as $obj) {

			// set fkey col in related ClientService rows to NULL
			$selectCriteria = new Criteria(ClientPeer::DATABASE_NAME);
			$updateValues = new Criteria(ClientPeer::DATABASE_NAME);
			$selectCriteria->add(ClientServicePeer::CLIENT_ID, $obj->getId());
			$updateValues->add(ClientServicePeer::CLIENT_ID, null);

					BasePeer::doUpdate($selectCriteria, $updateValues, $con); // use BasePeer because generated Peer doUpdate() methods only update using pkey

			// set fkey col in related NoteEntry rows to NULL
			$selectCriteria = new Criteria(ClientPeer::DATABASE_NAME);
			$updateValues = new Criteria(ClientPeer::DATABASE_NAME);
			$selectCriteria->add(NoteEntryPeer::CLIENT_ID, $obj->getId());
			$updateValues->add(NoteEntryPeer::CLIENT_ID, null);

					BasePeer::doUpdate($selectCriteria, $updateValues, $con); // use BasePeer because generated Peer doUpdate() methods only update using pkey

		}
	}

	/**
	 * Validates all modified columns of given Client object.
	 * If parameter $columns is either a single column name or an array of column names
	 * than only those columns are validated.
	 *
	 * NOTICE: This does not apply to primary or foreign keys for now.
	 *
	 * @param      Client $obj The object to validate.
	 * @param      mixed $cols Column name or array of column names.
	 *
	 * @return     mixed TRUE if all columns are valid or the error message of the first invalid column.
	 */
	public static function doValidate(Client $obj, $cols = null)
	{
		$columns = array();

		if ($cols) {
			$dbMap = Propel::getDatabaseMap(ClientPeer::DATABASE_NAME);
			$tableMap = $dbMap->getTable(ClientPeer::TABLE_NAME);

			if (! is_array($cols)) {
				$cols = array($cols);
			}

			foreach ($cols as $colName) {
				if ($tableMap->containsColumn($colName)) {
					$get = 'get' . $tableMap->getColumn($colName)->getPhpName();
					$columns[$colName] = $obj->$get();
				}
			}
		} else {

		}

		$res =  BasePeer::doValidate(ClientPeer::DATABASE_NAME, ClientPeer::TABLE_NAME, $columns);
    if ($res !== true) {
        foreach ($res as $failed) {
            $col = ClientPeer::translateFieldname($failed->getColumn(), BasePeer::TYPE_COLNAME, BasePeer::TYPE_PHPNAME);
        }
    }

    return $res;
	}

	/**
	 * Retrieve a single object by pkey.
	 *
	 * @param      int $pk the primary key.
	 * @param      PropelPDO $con the connection to use
	 * @return     Client
	 */
	public static function retrieveByPK($pk, PropelPDO $con = null)
	{

		if (null !== ($obj = ClientPeer::getInstanceFromPool((string) $pk))) {
			return $obj;
		}

		if ($con === null) {
			$con = Propel::getConnection(ClientPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria = new Criteria(ClientPeer::DATABASE_NAME);
		$criteria->add(ClientPeer::ID, $pk);

		$v = ClientPeer::doSelect($criteria, $con);

		return !empty($v) > 0 ? $v[0] : null;
	}

	/**
	 * Retrieve multiple objects by pkey.
	 *
	 * @param      array $pks List of primary keys
	 * @param      PropelPDO $con the connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function retrieveByPKs($pks, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(ClientPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$objs = null;
		if (empty($pks)) {
			$objs = array();
		} else {
			$criteria = new Criteria(ClientPeer::DATABASE_NAME);
			$criteria->add(ClientPeer::ID, $pks, Criteria::IN);
			$objs = ClientPeer::doSelect($criteria, $con);
		}
		return $objs;
	}

} // BaseClientPeer

// This is the static code needed to register the MapBuilder for this table with the main Propel class.
//
// NOTE: This static code cannot call methods on the ClientPeer class, because it is not defined yet.
// If you need to use overridden methods, you can add this code to the bottom of the ClientPeer class:
//
// Propel::getDatabaseMap(ClientPeer::DATABASE_NAME)->addTableBuilder(ClientPeer::TABLE_NAME, ClientPeer::getMapBuilder());
//
// Doing so will effectively overwrite the registration below.

Propel::getDatabaseMap(BaseClientPeer::DATABASE_NAME)->addTableBuilder(BaseClientPeer::TABLE_NAME, BaseClientPeer::getMapBuilder());

