<?php

/**
 * Base class that represents a row from the 'note_entry' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Tue Mar 29 20:17:55 2011
 *
 * @package    lib.model.om
 */
abstract class BaseNoteEntry extends BaseObject  implements Persistent {


  const PEER = 'NoteEntryPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        NoteEntryPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the employee_id field.
	 * @var        int
	 */
	protected $employee_id;

	/**
	 * The value for the client_id field.
	 * @var        int
	 */
	protected $client_id;

	/**
	 * The value for the client_service_id field.
	 * @var        int
	 */
	protected $client_service_id;

	/**
	 * The value for the office_id field.
	 * @var        int
	 */
	protected $office_id;

	/**
	 * The value for the frequency_id field.
	 * @var        int
	 */
	protected $frequency_id;

	/**
	 * The value for the service_date field.
	 * @var        string
	 */
	protected $service_date;

	/**
	 * The value for the time_in field.
	 * @var        string
	 */
	protected $time_in;

	/**
	 * The value for the time_out field.
	 * @var        string
	 */
	protected $time_out;

	/**
	 * The value for the cpt_code field.
	 * @var        string
	 */
	protected $cpt_code;

	/**
	 * The value for the units field.
	 * @var        string
	 */
	protected $units;

	/**
	 * The value for the absent field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $absent;

	/**
	 * The value for the comments field.
	 * @var        string
	 */
	protected $comments;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the updated_at field.
	 * @var        string
	 */
	protected $updated_at;

	/**
	 * @var        Employee
	 */
	protected $aEmployee;

	/**
	 * @var        Client
	 */
	protected $aClient;

	/**
	 * @var        ClientService
	 */
	protected $aClientService;

	/**
	 * @var        Office
	 */
	protected $aOffice;

	/**
	 * @var        Frequency
	 */
	protected $aFrequency;

	/**
	 * @var        array NoteEntryKids[] Collection to store aggregation of NoteEntryKids objects.
	 */
	protected $collNoteEntryKidss;

	/**
	 * @var        Criteria The criteria used to select the current contents of collNoteEntryKidss.
	 */
	private $lastNoteEntryKidsCriteria = null;

	/**
	 * @var        array EntryConcern[] Collection to store aggregation of EntryConcern objects.
	 */
	protected $collEntryConcerns;

	/**
	 * @var        Criteria The criteria used to select the current contents of collEntryConcerns.
	 */
	private $lastEntryConcernCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseNoteEntry object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->absent = 0;
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [employee_id] column value.
	 * 
	 * @return     int
	 */
	public function getEmployeeId()
	{
		return $this->employee_id;
	}

	/**
	 * Get the [client_id] column value.
	 * 
	 * @return     int
	 */
	public function getClientId()
	{
		return $this->client_id;
	}

	/**
	 * Get the [client_service_id] column value.
	 * 
	 * @return     int
	 */
	public function getClientServiceId()
	{
		return $this->client_service_id;
	}

	/**
	 * Get the [office_id] column value.
	 * 
	 * @return     int
	 */
	public function getOfficeId()
	{
		return $this->office_id;
	}

	/**
	 * Get the [frequency_id] column value.
	 * 
	 * @return     int
	 */
	public function getFrequencyId()
	{
		return $this->frequency_id;
	}

	/**
	 * Get the [optionally formatted] temporal [service_date] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getServiceDate($format = 'Y-m-d H:i:s')
	{
		if ($this->service_date === null) {
			return null;
		}


		if ($this->service_date === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->service_date);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->service_date, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [time_in] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getTimeIn($format = 'Y-m-d H:i:s')
	{
		if ($this->time_in === null) {
			return null;
		}


		if ($this->time_in === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->time_in);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->time_in, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [time_out] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getTimeOut($format = 'Y-m-d H:i:s')
	{
		if ($this->time_out === null) {
			return null;
		}


		if ($this->time_out === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->time_out);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->time_out, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [cpt_code] column value.
	 * 
	 * @return     string
	 */
	public function getCptCode()
	{
		return $this->cpt_code;
	}

	/**
	 * Get the [units] column value.
	 * 
	 * @return     string
	 */
	public function getUnits()
	{
		return $this->units;
	}

	/**
	 * Get the [absent] column value.
	 * 
	 * @return     int
	 */
	public function getAbsent()
	{
		return $this->absent;
	}

	/**
	 * Get the [comments] column value.
	 * 
	 * @return     string
	 */
	public function getComments()
	{
		return $this->comments;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}


		if ($this->created_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->created_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [updated_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->updated_at === null) {
			return null;
		}


		if ($this->updated_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->updated_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     NoteEntry The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = NoteEntryPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [employee_id] column.
	 * 
	 * @param      int $v new value
	 * @return     NoteEntry The current object (for fluent API support)
	 */
	public function setEmployeeId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->employee_id !== $v) {
			$this->employee_id = $v;
			$this->modifiedColumns[] = NoteEntryPeer::EMPLOYEE_ID;
		}

		if ($this->aEmployee !== null && $this->aEmployee->getId() !== $v) {
			$this->aEmployee = null;
		}

		return $this;
	} // setEmployeeId()

	/**
	 * Set the value of [client_id] column.
	 * 
	 * @param      int $v new value
	 * @return     NoteEntry The current object (for fluent API support)
	 */
	public function setClientId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->client_id !== $v) {
			$this->client_id = $v;
			$this->modifiedColumns[] = NoteEntryPeer::CLIENT_ID;
		}

		if ($this->aClient !== null && $this->aClient->getId() !== $v) {
			$this->aClient = null;
		}

		return $this;
	} // setClientId()

	/**
	 * Set the value of [client_service_id] column.
	 * 
	 * @param      int $v new value
	 * @return     NoteEntry The current object (for fluent API support)
	 */
	public function setClientServiceId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->client_service_id !== $v) {
			$this->client_service_id = $v;
			$this->modifiedColumns[] = NoteEntryPeer::CLIENT_SERVICE_ID;
		}

		if ($this->aClientService !== null && $this->aClientService->getId() !== $v) {
			$this->aClientService = null;
		}

		return $this;
	} // setClientServiceId()

	/**
	 * Set the value of [office_id] column.
	 * 
	 * @param      int $v new value
	 * @return     NoteEntry The current object (for fluent API support)
	 */
	public function setOfficeId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->office_id !== $v) {
			$this->office_id = $v;
			$this->modifiedColumns[] = NoteEntryPeer::OFFICE_ID;
		}

		if ($this->aOffice !== null && $this->aOffice->getId() !== $v) {
			$this->aOffice = null;
		}

		return $this;
	} // setOfficeId()

	/**
	 * Set the value of [frequency_id] column.
	 * 
	 * @param      int $v new value
	 * @return     NoteEntry The current object (for fluent API support)
	 */
	public function setFrequencyId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->frequency_id !== $v) {
			$this->frequency_id = $v;
			$this->modifiedColumns[] = NoteEntryPeer::FREQUENCY_ID;
		}

		if ($this->aFrequency !== null && $this->aFrequency->getId() !== $v) {
			$this->aFrequency = null;
		}

		return $this;
	} // setFrequencyId()

	/**
	 * Sets the value of [service_date] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     NoteEntry The current object (for fluent API support)
	 */
	public function setServiceDate($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->service_date !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->service_date !== null && $tmpDt = new DateTime($this->service_date)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->service_date = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = NoteEntryPeer::SERVICE_DATE;
			}
		} // if either are not null

		return $this;
	} // setServiceDate()

	/**
	 * Sets the value of [time_in] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     NoteEntry The current object (for fluent API support)
	 */
	public function setTimeIn($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->time_in !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->time_in !== null && $tmpDt = new DateTime($this->time_in)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->time_in = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = NoteEntryPeer::TIME_IN;
			}
		} // if either are not null

		return $this;
	} // setTimeIn()

	/**
	 * Sets the value of [time_out] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     NoteEntry The current object (for fluent API support)
	 */
	public function setTimeOut($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->time_out !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->time_out !== null && $tmpDt = new DateTime($this->time_out)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->time_out = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = NoteEntryPeer::TIME_OUT;
			}
		} // if either are not null

		return $this;
	} // setTimeOut()

	/**
	 * Set the value of [cpt_code] column.
	 * 
	 * @param      string $v new value
	 * @return     NoteEntry The current object (for fluent API support)
	 */
	public function setCptCode($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->cpt_code !== $v) {
			$this->cpt_code = $v;
			$this->modifiedColumns[] = NoteEntryPeer::CPT_CODE;
		}

		return $this;
	} // setCptCode()

	/**
	 * Set the value of [units] column.
	 * 
	 * @param      string $v new value
	 * @return     NoteEntry The current object (for fluent API support)
	 */
	public function setUnits($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->units !== $v) {
			$this->units = $v;
			$this->modifiedColumns[] = NoteEntryPeer::UNITS;
		}

		return $this;
	} // setUnits()

	/**
	 * Set the value of [absent] column.
	 * 
	 * @param      int $v new value
	 * @return     NoteEntry The current object (for fluent API support)
	 */
	public function setAbsent($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->absent !== $v || $v === 0) {
			$this->absent = $v;
			$this->modifiedColumns[] = NoteEntryPeer::ABSENT;
		}

		return $this;
	} // setAbsent()

	/**
	 * Set the value of [comments] column.
	 * 
	 * @param      string $v new value
	 * @return     NoteEntry The current object (for fluent API support)
	 */
	public function setComments($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->comments !== $v) {
			$this->comments = $v;
			$this->modifiedColumns[] = NoteEntryPeer::COMMENTS;
		}

		return $this;
	} // setComments()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     NoteEntry The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = NoteEntryPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     NoteEntry The current object (for fluent API support)
	 */
	public function setUpdatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->updated_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->updated_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = NoteEntryPeer::UPDATED_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdatedAt()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array(NoteEntryPeer::ABSENT))) {
				return false;
			}

			if ($this->absent !== 0) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->employee_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->client_id = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->client_service_id = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->office_id = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
			$this->frequency_id = ($row[$startcol + 5] !== null) ? (int) $row[$startcol + 5] : null;
			$this->service_date = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->time_in = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->time_out = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->cpt_code = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->units = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->absent = ($row[$startcol + 11] !== null) ? (int) $row[$startcol + 11] : null;
			$this->comments = ($row[$startcol + 12] !== null) ? (string) $row[$startcol + 12] : null;
			$this->created_at = ($row[$startcol + 13] !== null) ? (string) $row[$startcol + 13] : null;
			$this->updated_at = ($row[$startcol + 14] !== null) ? (string) $row[$startcol + 14] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 15; // 15 = NoteEntryPeer::NUM_COLUMNS - NoteEntryPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating NoteEntry object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aEmployee !== null && $this->employee_id !== $this->aEmployee->getId()) {
			$this->aEmployee = null;
		}
		if ($this->aClient !== null && $this->client_id !== $this->aClient->getId()) {
			$this->aClient = null;
		}
		if ($this->aClientService !== null && $this->client_service_id !== $this->aClientService->getId()) {
			$this->aClientService = null;
		}
		if ($this->aOffice !== null && $this->office_id !== $this->aOffice->getId()) {
			$this->aOffice = null;
		}
		if ($this->aFrequency !== null && $this->frequency_id !== $this->aFrequency->getId()) {
			$this->aFrequency = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(NoteEntryPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = NoteEntryPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aEmployee = null;
			$this->aClient = null;
			$this->aClientService = null;
			$this->aOffice = null;
			$this->aFrequency = null;
			$this->collNoteEntryKidss = null;
			$this->lastNoteEntryKidsCriteria = null;

			$this->collEntryConcerns = null;
			$this->lastEntryConcernCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseNoteEntry:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(NoteEntryPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			NoteEntryPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseNoteEntry:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseNoteEntry:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


    if ($this->isNew() && !$this->isColumnModified(NoteEntryPeer::CREATED_AT))
    {
      $this->setCreatedAt(time());
    }

    if ($this->isModified() && !$this->isColumnModified(NoteEntryPeer::UPDATED_AT))
    {
      $this->setUpdatedAt(time());
    }

		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(NoteEntryPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseNoteEntry:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			NoteEntryPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aEmployee !== null) {
				if ($this->aEmployee->isModified() || $this->aEmployee->isNew()) {
					$affectedRows += $this->aEmployee->save($con);
				}
				$this->setEmployee($this->aEmployee);
			}

			if ($this->aClient !== null) {
				if ($this->aClient->isModified() || $this->aClient->isNew()) {
					$affectedRows += $this->aClient->save($con);
				}
				$this->setClient($this->aClient);
			}

			if ($this->aClientService !== null) {
				if ($this->aClientService->isModified() || $this->aClientService->isNew()) {
					$affectedRows += $this->aClientService->save($con);
				}
				$this->setClientService($this->aClientService);
			}

			if ($this->aOffice !== null) {
				if ($this->aOffice->isModified() || $this->aOffice->isNew()) {
					$affectedRows += $this->aOffice->save($con);
				}
				$this->setOffice($this->aOffice);
			}

			if ($this->aFrequency !== null) {
				if ($this->aFrequency->isModified() || $this->aFrequency->isNew()) {
					$affectedRows += $this->aFrequency->save($con);
				}
				$this->setFrequency($this->aFrequency);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = NoteEntryPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = NoteEntryPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += NoteEntryPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collNoteEntryKidss !== null) {
				foreach ($this->collNoteEntryKidss as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collEntryConcerns !== null) {
				foreach ($this->collEntryConcerns as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aEmployee !== null) {
				if (!$this->aEmployee->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aEmployee->getValidationFailures());
				}
			}

			if ($this->aClient !== null) {
				if (!$this->aClient->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aClient->getValidationFailures());
				}
			}

			if ($this->aClientService !== null) {
				if (!$this->aClientService->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aClientService->getValidationFailures());
				}
			}

			if ($this->aOffice !== null) {
				if (!$this->aOffice->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aOffice->getValidationFailures());
				}
			}

			if ($this->aFrequency !== null) {
				if (!$this->aFrequency->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aFrequency->getValidationFailures());
				}
			}


			if (($retval = NoteEntryPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collNoteEntryKidss !== null) {
					foreach ($this->collNoteEntryKidss as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collEntryConcerns !== null) {
					foreach ($this->collEntryConcerns as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = NoteEntryPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getEmployeeId();
				break;
			case 2:
				return $this->getClientId();
				break;
			case 3:
				return $this->getClientServiceId();
				break;
			case 4:
				return $this->getOfficeId();
				break;
			case 5:
				return $this->getFrequencyId();
				break;
			case 6:
				return $this->getServiceDate();
				break;
			case 7:
				return $this->getTimeIn();
				break;
			case 8:
				return $this->getTimeOut();
				break;
			case 9:
				return $this->getCptCode();
				break;
			case 10:
				return $this->getUnits();
				break;
			case 11:
				return $this->getAbsent();
				break;
			case 12:
				return $this->getComments();
				break;
			case 13:
				return $this->getCreatedAt();
				break;
			case 14:
				return $this->getUpdatedAt();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = NoteEntryPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getEmployeeId(),
			$keys[2] => $this->getClientId(),
			$keys[3] => $this->getClientServiceId(),
			$keys[4] => $this->getOfficeId(),
			$keys[5] => $this->getFrequencyId(),
			$keys[6] => $this->getServiceDate(),
			$keys[7] => $this->getTimeIn(),
			$keys[8] => $this->getTimeOut(),
			$keys[9] => $this->getCptCode(),
			$keys[10] => $this->getUnits(),
			$keys[11] => $this->getAbsent(),
			$keys[12] => $this->getComments(),
			$keys[13] => $this->getCreatedAt(),
			$keys[14] => $this->getUpdatedAt(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = NoteEntryPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setEmployeeId($value);
				break;
			case 2:
				$this->setClientId($value);
				break;
			case 3:
				$this->setClientServiceId($value);
				break;
			case 4:
				$this->setOfficeId($value);
				break;
			case 5:
				$this->setFrequencyId($value);
				break;
			case 6:
				$this->setServiceDate($value);
				break;
			case 7:
				$this->setTimeIn($value);
				break;
			case 8:
				$this->setTimeOut($value);
				break;
			case 9:
				$this->setCptCode($value);
				break;
			case 10:
				$this->setUnits($value);
				break;
			case 11:
				$this->setAbsent($value);
				break;
			case 12:
				$this->setComments($value);
				break;
			case 13:
				$this->setCreatedAt($value);
				break;
			case 14:
				$this->setUpdatedAt($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = NoteEntryPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setEmployeeId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setClientId($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setClientServiceId($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setOfficeId($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setFrequencyId($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setServiceDate($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setTimeIn($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setTimeOut($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setCptCode($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setUnits($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setAbsent($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setComments($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setCreatedAt($arr[$keys[13]]);
		if (array_key_exists($keys[14], $arr)) $this->setUpdatedAt($arr[$keys[14]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(NoteEntryPeer::DATABASE_NAME);

		if ($this->isColumnModified(NoteEntryPeer::ID)) $criteria->add(NoteEntryPeer::ID, $this->id);
		if ($this->isColumnModified(NoteEntryPeer::EMPLOYEE_ID)) $criteria->add(NoteEntryPeer::EMPLOYEE_ID, $this->employee_id);
		if ($this->isColumnModified(NoteEntryPeer::CLIENT_ID)) $criteria->add(NoteEntryPeer::CLIENT_ID, $this->client_id);
		if ($this->isColumnModified(NoteEntryPeer::CLIENT_SERVICE_ID)) $criteria->add(NoteEntryPeer::CLIENT_SERVICE_ID, $this->client_service_id);
		if ($this->isColumnModified(NoteEntryPeer::OFFICE_ID)) $criteria->add(NoteEntryPeer::OFFICE_ID, $this->office_id);
		if ($this->isColumnModified(NoteEntryPeer::FREQUENCY_ID)) $criteria->add(NoteEntryPeer::FREQUENCY_ID, $this->frequency_id);
		if ($this->isColumnModified(NoteEntryPeer::SERVICE_DATE)) $criteria->add(NoteEntryPeer::SERVICE_DATE, $this->service_date);
		if ($this->isColumnModified(NoteEntryPeer::TIME_IN)) $criteria->add(NoteEntryPeer::TIME_IN, $this->time_in);
		if ($this->isColumnModified(NoteEntryPeer::TIME_OUT)) $criteria->add(NoteEntryPeer::TIME_OUT, $this->time_out);
		if ($this->isColumnModified(NoteEntryPeer::CPT_CODE)) $criteria->add(NoteEntryPeer::CPT_CODE, $this->cpt_code);
		if ($this->isColumnModified(NoteEntryPeer::UNITS)) $criteria->add(NoteEntryPeer::UNITS, $this->units);
		if ($this->isColumnModified(NoteEntryPeer::ABSENT)) $criteria->add(NoteEntryPeer::ABSENT, $this->absent);
		if ($this->isColumnModified(NoteEntryPeer::COMMENTS)) $criteria->add(NoteEntryPeer::COMMENTS, $this->comments);
		if ($this->isColumnModified(NoteEntryPeer::CREATED_AT)) $criteria->add(NoteEntryPeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(NoteEntryPeer::UPDATED_AT)) $criteria->add(NoteEntryPeer::UPDATED_AT, $this->updated_at);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(NoteEntryPeer::DATABASE_NAME);

		$criteria->add(NoteEntryPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of NoteEntry (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setEmployeeId($this->employee_id);

		$copyObj->setClientId($this->client_id);

		$copyObj->setClientServiceId($this->client_service_id);

		$copyObj->setOfficeId($this->office_id);

		$copyObj->setFrequencyId($this->frequency_id);

		$copyObj->setServiceDate($this->service_date);

		$copyObj->setTimeIn($this->time_in);

		$copyObj->setTimeOut($this->time_out);

		$copyObj->setCptCode($this->cpt_code);

		$copyObj->setUnits($this->units);

		$copyObj->setAbsent($this->absent);

		$copyObj->setComments($this->comments);

		$copyObj->setCreatedAt($this->created_at);

		$copyObj->setUpdatedAt($this->updated_at);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getNoteEntryKidss() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addNoteEntryKids($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getEntryConcerns() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addEntryConcern($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     NoteEntry Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     NoteEntryPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new NoteEntryPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Employee object.
	 *
	 * @param      Employee $v
	 * @return     NoteEntry The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setEmployee(Employee $v = null)
	{
		if ($v === null) {
			$this->setEmployeeId(NULL);
		} else {
			$this->setEmployeeId($v->getId());
		}

		$this->aEmployee = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Employee object, it will not be re-added.
		if ($v !== null) {
			$v->addNoteEntry($this);
		}

		return $this;
	}


	/**
	 * Get the associated Employee object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Employee The associated Employee object.
	 * @throws     PropelException
	 */
	public function getEmployee(PropelPDO $con = null)
	{
		if ($this->aEmployee === null && ($this->employee_id !== null)) {
			$c = new Criteria(EmployeePeer::DATABASE_NAME);
			$c->add(EmployeePeer::ID, $this->employee_id);
			$this->aEmployee = EmployeePeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aEmployee->addNoteEntrys($this);
			 */
		}
		return $this->aEmployee;
	}

	/**
	 * Declares an association between this object and a Client object.
	 *
	 * @param      Client $v
	 * @return     NoteEntry The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setClient(Client $v = null)
	{
		if ($v === null) {
			$this->setClientId(NULL);
		} else {
			$this->setClientId($v->getId());
		}

		$this->aClient = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Client object, it will not be re-added.
		if ($v !== null) {
			$v->addNoteEntry($this);
		}

		return $this;
	}


	/**
	 * Get the associated Client object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Client The associated Client object.
	 * @throws     PropelException
	 */
	public function getClient(PropelPDO $con = null)
	{
		if ($this->aClient === null && ($this->client_id !== null)) {
			$c = new Criteria(ClientPeer::DATABASE_NAME);
			$c->add(ClientPeer::ID, $this->client_id);
			$this->aClient = ClientPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aClient->addNoteEntrys($this);
			 */
		}
		return $this->aClient;
	}

	/**
	 * Declares an association between this object and a ClientService object.
	 *
	 * @param      ClientService $v
	 * @return     NoteEntry The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setClientService(ClientService $v = null)
	{
		if ($v === null) {
			$this->setClientServiceId(NULL);
		} else {
			$this->setClientServiceId($v->getId());
		}

		$this->aClientService = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the ClientService object, it will not be re-added.
		if ($v !== null) {
			$v->addNoteEntry($this);
		}

		return $this;
	}


	/**
	 * Get the associated ClientService object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     ClientService The associated ClientService object.
	 * @throws     PropelException
	 */
	public function getClientService(PropelPDO $con = null)
	{
		if ($this->aClientService === null && ($this->client_service_id !== null)) {
			$c = new Criteria(ClientServicePeer::DATABASE_NAME);
			$c->add(ClientServicePeer::ID, $this->client_service_id);
			$this->aClientService = ClientServicePeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aClientService->addNoteEntrys($this);
			 */
		}
		return $this->aClientService;
	}

	/**
	 * Declares an association between this object and a Office object.
	 *
	 * @param      Office $v
	 * @return     NoteEntry The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setOffice(Office $v = null)
	{
		if ($v === null) {
			$this->setOfficeId(NULL);
		} else {
			$this->setOfficeId($v->getId());
		}

		$this->aOffice = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Office object, it will not be re-added.
		if ($v !== null) {
			$v->addNoteEntry($this);
		}

		return $this;
	}


	/**
	 * Get the associated Office object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Office The associated Office object.
	 * @throws     PropelException
	 */
	public function getOffice(PropelPDO $con = null)
	{
		if ($this->aOffice === null && ($this->office_id !== null)) {
			$c = new Criteria(OfficePeer::DATABASE_NAME);
			$c->add(OfficePeer::ID, $this->office_id);
			$this->aOffice = OfficePeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aOffice->addNoteEntrys($this);
			 */
		}
		return $this->aOffice;
	}

	/**
	 * Declares an association between this object and a Frequency object.
	 *
	 * @param      Frequency $v
	 * @return     NoteEntry The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setFrequency(Frequency $v = null)
	{
		if ($v === null) {
			$this->setFrequencyId(NULL);
		} else {
			$this->setFrequencyId($v->getId());
		}

		$this->aFrequency = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Frequency object, it will not be re-added.
		if ($v !== null) {
			$v->addNoteEntry($this);
		}

		return $this;
	}


	/**
	 * Get the associated Frequency object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Frequency The associated Frequency object.
	 * @throws     PropelException
	 */
	public function getFrequency(PropelPDO $con = null)
	{
		if ($this->aFrequency === null && ($this->frequency_id !== null)) {
			$c = new Criteria(FrequencyPeer::DATABASE_NAME);
			$c->add(FrequencyPeer::ID, $this->frequency_id);
			$this->aFrequency = FrequencyPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aFrequency->addNoteEntrys($this);
			 */
		}
		return $this->aFrequency;
	}

	/**
	 * Clears out the collNoteEntryKidss collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addNoteEntryKidss()
	 */
	public function clearNoteEntryKidss()
	{
		$this->collNoteEntryKidss = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collNoteEntryKidss collection (array).
	 *
	 * By default this just sets the collNoteEntryKidss collection to an empty array (like clearcollNoteEntryKidss());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initNoteEntryKidss()
	{
		$this->collNoteEntryKidss = array();
	}

	/**
	 * Gets an array of NoteEntryKids objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this NoteEntry has previously been saved, it will retrieve
	 * related NoteEntryKidss from storage. If this NoteEntry is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array NoteEntryKids[]
	 * @throws     PropelException
	 */
	public function getNoteEntryKidss($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(NoteEntryPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collNoteEntryKidss === null) {
			if ($this->isNew()) {
			   $this->collNoteEntryKidss = array();
			} else {

				$criteria->add(NoteEntryKidsPeer::NOTE_ENTRY_ID, $this->id);

				NoteEntryKidsPeer::addSelectColumns($criteria);
				$this->collNoteEntryKidss = NoteEntryKidsPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(NoteEntryKidsPeer::NOTE_ENTRY_ID, $this->id);

				NoteEntryKidsPeer::addSelectColumns($criteria);
				if (!isset($this->lastNoteEntryKidsCriteria) || !$this->lastNoteEntryKidsCriteria->equals($criteria)) {
					$this->collNoteEntryKidss = NoteEntryKidsPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastNoteEntryKidsCriteria = $criteria;
		return $this->collNoteEntryKidss;
	}

	/**
	 * Returns the number of related NoteEntryKids objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related NoteEntryKids objects.
	 * @throws     PropelException
	 */
	public function countNoteEntryKidss(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(NoteEntryPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collNoteEntryKidss === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(NoteEntryKidsPeer::NOTE_ENTRY_ID, $this->id);

				$count = NoteEntryKidsPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(NoteEntryKidsPeer::NOTE_ENTRY_ID, $this->id);

				if (!isset($this->lastNoteEntryKidsCriteria) || !$this->lastNoteEntryKidsCriteria->equals($criteria)) {
					$count = NoteEntryKidsPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collNoteEntryKidss);
				}
			} else {
				$count = count($this->collNoteEntryKidss);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a NoteEntryKids object to this object
	 * through the NoteEntryKids foreign key attribute.
	 *
	 * @param      NoteEntryKids $l NoteEntryKids
	 * @return     void
	 * @throws     PropelException
	 */
	public function addNoteEntryKids(NoteEntryKids $l)
	{
		if ($this->collNoteEntryKidss === null) {
			$this->initNoteEntryKidss();
		}
		if (!in_array($l, $this->collNoteEntryKidss, true)) { // only add it if the **same** object is not already associated
			array_push($this->collNoteEntryKidss, $l);
			$l->setNoteEntry($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this NoteEntry is new, it will return
	 * an empty collection; or if this NoteEntry has previously
	 * been saved, it will retrieve related NoteEntryKidss from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in NoteEntry.
	 */
	public function getNoteEntryKidssJoinClient($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(NoteEntryPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collNoteEntryKidss === null) {
			if ($this->isNew()) {
				$this->collNoteEntryKidss = array();
			} else {

				$criteria->add(NoteEntryKidsPeer::NOTE_ENTRY_ID, $this->id);

				$this->collNoteEntryKidss = NoteEntryKidsPeer::doSelectJoinClient($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(NoteEntryKidsPeer::NOTE_ENTRY_ID, $this->id);

			if (!isset($this->lastNoteEntryKidsCriteria) || !$this->lastNoteEntryKidsCriteria->equals($criteria)) {
				$this->collNoteEntryKidss = NoteEntryKidsPeer::doSelectJoinClient($criteria, $con, $join_behavior);
			}
		}
		$this->lastNoteEntryKidsCriteria = $criteria;

		return $this->collNoteEntryKidss;
	}

	/**
	 * Clears out the collEntryConcerns collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addEntryConcerns()
	 */
	public function clearEntryConcerns()
	{
		$this->collEntryConcerns = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collEntryConcerns collection (array).
	 *
	 * By default this just sets the collEntryConcerns collection to an empty array (like clearcollEntryConcerns());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initEntryConcerns()
	{
		$this->collEntryConcerns = array();
	}

	/**
	 * Gets an array of EntryConcern objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this NoteEntry has previously been saved, it will retrieve
	 * related EntryConcerns from storage. If this NoteEntry is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array EntryConcern[]
	 * @throws     PropelException
	 */
	public function getEntryConcerns($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(NoteEntryPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collEntryConcerns === null) {
			if ($this->isNew()) {
			   $this->collEntryConcerns = array();
			} else {

				$criteria->add(EntryConcernPeer::NOTE_ENTRY_ID, $this->id);

				EntryConcernPeer::addSelectColumns($criteria);
				$this->collEntryConcerns = EntryConcernPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(EntryConcernPeer::NOTE_ENTRY_ID, $this->id);

				EntryConcernPeer::addSelectColumns($criteria);
				if (!isset($this->lastEntryConcernCriteria) || !$this->lastEntryConcernCriteria->equals($criteria)) {
					$this->collEntryConcerns = EntryConcernPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastEntryConcernCriteria = $criteria;
		return $this->collEntryConcerns;
	}

	/**
	 * Returns the number of related EntryConcern objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related EntryConcern objects.
	 * @throws     PropelException
	 */
	public function countEntryConcerns(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(NoteEntryPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collEntryConcerns === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(EntryConcernPeer::NOTE_ENTRY_ID, $this->id);

				$count = EntryConcernPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(EntryConcernPeer::NOTE_ENTRY_ID, $this->id);

				if (!isset($this->lastEntryConcernCriteria) || !$this->lastEntryConcernCriteria->equals($criteria)) {
					$count = EntryConcernPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collEntryConcerns);
				}
			} else {
				$count = count($this->collEntryConcerns);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a EntryConcern object to this object
	 * through the EntryConcern foreign key attribute.
	 *
	 * @param      EntryConcern $l EntryConcern
	 * @return     void
	 * @throws     PropelException
	 */
	public function addEntryConcern(EntryConcern $l)
	{
		if ($this->collEntryConcerns === null) {
			$this->initEntryConcerns();
		}
		if (!in_array($l, $this->collEntryConcerns, true)) { // only add it if the **same** object is not already associated
			array_push($this->collEntryConcerns, $l);
			$l->setNoteEntry($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this NoteEntry is new, it will return
	 * an empty collection; or if this NoteEntry has previously
	 * been saved, it will retrieve related EntryConcerns from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in NoteEntry.
	 */
	public function getEntryConcernsJoinAreaOfConcern($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(NoteEntryPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collEntryConcerns === null) {
			if ($this->isNew()) {
				$this->collEntryConcerns = array();
			} else {

				$criteria->add(EntryConcernPeer::NOTE_ENTRY_ID, $this->id);

				$this->collEntryConcerns = EntryConcernPeer::doSelectJoinAreaOfConcern($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(EntryConcernPeer::NOTE_ENTRY_ID, $this->id);

			if (!isset($this->lastEntryConcernCriteria) || !$this->lastEntryConcernCriteria->equals($criteria)) {
				$this->collEntryConcerns = EntryConcernPeer::doSelectJoinAreaOfConcern($criteria, $con, $join_behavior);
			}
		}
		$this->lastEntryConcernCriteria = $criteria;

		return $this->collEntryConcerns;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this NoteEntry is new, it will return
	 * an empty collection; or if this NoteEntry has previously
	 * been saved, it will retrieve related EntryConcerns from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in NoteEntry.
	 */
	public function getEntryConcernsJoinObjective($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(NoteEntryPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collEntryConcerns === null) {
			if ($this->isNew()) {
				$this->collEntryConcerns = array();
			} else {

				$criteria->add(EntryConcernPeer::NOTE_ENTRY_ID, $this->id);

				$this->collEntryConcerns = EntryConcernPeer::doSelectJoinObjective($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(EntryConcernPeer::NOTE_ENTRY_ID, $this->id);

			if (!isset($this->lastEntryConcernCriteria) || !$this->lastEntryConcernCriteria->equals($criteria)) {
				$this->collEntryConcerns = EntryConcernPeer::doSelectJoinObjective($criteria, $con, $join_behavior);
			}
		}
		$this->lastEntryConcernCriteria = $criteria;

		return $this->collEntryConcerns;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this NoteEntry is new, it will return
	 * an empty collection; or if this NoteEntry has previously
	 * been saved, it will retrieve related EntryConcerns from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in NoteEntry.
	 */
	public function getEntryConcernsJoinPrompt($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(NoteEntryPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collEntryConcerns === null) {
			if ($this->isNew()) {
				$this->collEntryConcerns = array();
			} else {

				$criteria->add(EntryConcernPeer::NOTE_ENTRY_ID, $this->id);

				$this->collEntryConcerns = EntryConcernPeer::doSelectJoinPrompt($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(EntryConcernPeer::NOTE_ENTRY_ID, $this->id);

			if (!isset($this->lastEntryConcernCriteria) || !$this->lastEntryConcernCriteria->equals($criteria)) {
				$this->collEntryConcerns = EntryConcernPeer::doSelectJoinPrompt($criteria, $con, $join_behavior);
			}
		}
		$this->lastEntryConcernCriteria = $criteria;

		return $this->collEntryConcerns;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this NoteEntry is new, it will return
	 * an empty collection; or if this NoteEntry has previously
	 * been saved, it will retrieve related EntryConcerns from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in NoteEntry.
	 */
	public function getEntryConcernsJoinLevel($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(NoteEntryPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collEntryConcerns === null) {
			if ($this->isNew()) {
				$this->collEntryConcerns = array();
			} else {

				$criteria->add(EntryConcernPeer::NOTE_ENTRY_ID, $this->id);

				$this->collEntryConcerns = EntryConcernPeer::doSelectJoinLevel($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(EntryConcernPeer::NOTE_ENTRY_ID, $this->id);

			if (!isset($this->lastEntryConcernCriteria) || !$this->lastEntryConcernCriteria->equals($criteria)) {
				$this->collEntryConcerns = EntryConcernPeer::doSelectJoinLevel($criteria, $con, $join_behavior);
			}
		}
		$this->lastEntryConcernCriteria = $criteria;

		return $this->collEntryConcerns;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collNoteEntryKidss) {
				foreach ((array) $this->collNoteEntryKidss as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collEntryConcerns) {
				foreach ((array) $this->collEntryConcerns as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collNoteEntryKidss = null;
		$this->collEntryConcerns = null;
			$this->aEmployee = null;
			$this->aClient = null;
			$this->aClientService = null;
			$this->aOffice = null;
			$this->aFrequency = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseNoteEntry:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseNoteEntry::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseNoteEntry
