<?php

/**
 * Base class that represents a row from the 'objective' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Tue Mar 29 20:17:55 2011
 *
 * @package    lib.model.om
 */
abstract class BaseObjective extends BaseObject  implements Persistent {


  const PEER = 'ObjectivePeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        ObjectivePeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the short_name field.
	 * @var        string
	 */
	protected $short_name;

	/**
	 * The value for the long_name field.
	 * @var        string
	 */
	protected $long_name;

	/**
	 * The value for the area_of_concern_id field.
	 * @var        int
	 */
	protected $area_of_concern_id;

	/**
	 * @var        AreaOfConcern
	 */
	protected $aAreaOfConcern;

	/**
	 * @var        array Prompt[] Collection to store aggregation of Prompt objects.
	 */
	protected $collPrompts;

	/**
	 * @var        Criteria The criteria used to select the current contents of collPrompts.
	 */
	private $lastPromptCriteria = null;

	/**
	 * @var        array EntryConcern[] Collection to store aggregation of EntryConcern objects.
	 */
	protected $collEntryConcerns;

	/**
	 * @var        Criteria The criteria used to select the current contents of collEntryConcerns.
	 */
	private $lastEntryConcernCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseObjective object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [short_name] column value.
	 * 
	 * @return     string
	 */
	public function getShortName()
	{
		return $this->short_name;
	}

	/**
	 * Get the [long_name] column value.
	 * 
	 * @return     string
	 */
	public function getLongName()
	{
		return $this->long_name;
	}

	/**
	 * Get the [area_of_concern_id] column value.
	 * 
	 * @return     int
	 */
	public function getAreaOfConcernId()
	{
		return $this->area_of_concern_id;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Objective The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = ObjectivePeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [short_name] column.
	 * 
	 * @param      string $v new value
	 * @return     Objective The current object (for fluent API support)
	 */
	public function setShortName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->short_name !== $v) {
			$this->short_name = $v;
			$this->modifiedColumns[] = ObjectivePeer::SHORT_NAME;
		}

		return $this;
	} // setShortName()

	/**
	 * Set the value of [long_name] column.
	 * 
	 * @param      string $v new value
	 * @return     Objective The current object (for fluent API support)
	 */
	public function setLongName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->long_name !== $v) {
			$this->long_name = $v;
			$this->modifiedColumns[] = ObjectivePeer::LONG_NAME;
		}

		return $this;
	} // setLongName()

	/**
	 * Set the value of [area_of_concern_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Objective The current object (for fluent API support)
	 */
	public function setAreaOfConcernId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->area_of_concern_id !== $v) {
			$this->area_of_concern_id = $v;
			$this->modifiedColumns[] = ObjectivePeer::AREA_OF_CONCERN_ID;
		}

		if ($this->aAreaOfConcern !== null && $this->aAreaOfConcern->getId() !== $v) {
			$this->aAreaOfConcern = null;
		}

		return $this;
	} // setAreaOfConcernId()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->short_name = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->long_name = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->area_of_concern_id = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 4; // 4 = ObjectivePeer::NUM_COLUMNS - ObjectivePeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Objective object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aAreaOfConcern !== null && $this->area_of_concern_id !== $this->aAreaOfConcern->getId()) {
			$this->aAreaOfConcern = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ObjectivePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = ObjectivePeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aAreaOfConcern = null;
			$this->collPrompts = null;
			$this->lastPromptCriteria = null;

			$this->collEntryConcerns = null;
			$this->lastEntryConcernCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseObjective:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ObjectivePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			ObjectivePeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseObjective:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseObjective:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ObjectivePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseObjective:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			ObjectivePeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aAreaOfConcern !== null) {
				if ($this->aAreaOfConcern->isModified() || $this->aAreaOfConcern->isNew()) {
					$affectedRows += $this->aAreaOfConcern->save($con);
				}
				$this->setAreaOfConcern($this->aAreaOfConcern);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = ObjectivePeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = ObjectivePeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += ObjectivePeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collPrompts !== null) {
				foreach ($this->collPrompts as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collEntryConcerns !== null) {
				foreach ($this->collEntryConcerns as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aAreaOfConcern !== null) {
				if (!$this->aAreaOfConcern->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aAreaOfConcern->getValidationFailures());
				}
			}


			if (($retval = ObjectivePeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collPrompts !== null) {
					foreach ($this->collPrompts as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collEntryConcerns !== null) {
					foreach ($this->collEntryConcerns as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = ObjectivePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getShortName();
				break;
			case 2:
				return $this->getLongName();
				break;
			case 3:
				return $this->getAreaOfConcernId();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = ObjectivePeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getShortName(),
			$keys[2] => $this->getLongName(),
			$keys[3] => $this->getAreaOfConcernId(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = ObjectivePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setShortName($value);
				break;
			case 2:
				$this->setLongName($value);
				break;
			case 3:
				$this->setAreaOfConcernId($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = ObjectivePeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setShortName($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setLongName($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setAreaOfConcernId($arr[$keys[3]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(ObjectivePeer::DATABASE_NAME);

		if ($this->isColumnModified(ObjectivePeer::ID)) $criteria->add(ObjectivePeer::ID, $this->id);
		if ($this->isColumnModified(ObjectivePeer::SHORT_NAME)) $criteria->add(ObjectivePeer::SHORT_NAME, $this->short_name);
		if ($this->isColumnModified(ObjectivePeer::LONG_NAME)) $criteria->add(ObjectivePeer::LONG_NAME, $this->long_name);
		if ($this->isColumnModified(ObjectivePeer::AREA_OF_CONCERN_ID)) $criteria->add(ObjectivePeer::AREA_OF_CONCERN_ID, $this->area_of_concern_id);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(ObjectivePeer::DATABASE_NAME);

		$criteria->add(ObjectivePeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Objective (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setShortName($this->short_name);

		$copyObj->setLongName($this->long_name);

		$copyObj->setAreaOfConcernId($this->area_of_concern_id);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getPrompts() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addPrompt($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getEntryConcerns() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addEntryConcern($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Objective Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     ObjectivePeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new ObjectivePeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a AreaOfConcern object.
	 *
	 * @param      AreaOfConcern $v
	 * @return     Objective The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setAreaOfConcern(AreaOfConcern $v = null)
	{
		if ($v === null) {
			$this->setAreaOfConcernId(NULL);
		} else {
			$this->setAreaOfConcernId($v->getId());
		}

		$this->aAreaOfConcern = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the AreaOfConcern object, it will not be re-added.
		if ($v !== null) {
			$v->addObjective($this);
		}

		return $this;
	}


	/**
	 * Get the associated AreaOfConcern object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     AreaOfConcern The associated AreaOfConcern object.
	 * @throws     PropelException
	 */
	public function getAreaOfConcern(PropelPDO $con = null)
	{
		if ($this->aAreaOfConcern === null && ($this->area_of_concern_id !== null)) {
			$c = new Criteria(AreaOfConcernPeer::DATABASE_NAME);
			$c->add(AreaOfConcernPeer::ID, $this->area_of_concern_id);
			$this->aAreaOfConcern = AreaOfConcernPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aAreaOfConcern->addObjectives($this);
			 */
		}
		return $this->aAreaOfConcern;
	}

	/**
	 * Clears out the collPrompts collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addPrompts()
	 */
	public function clearPrompts()
	{
		$this->collPrompts = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collPrompts collection (array).
	 *
	 * By default this just sets the collPrompts collection to an empty array (like clearcollPrompts());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initPrompts()
	{
		$this->collPrompts = array();
	}

	/**
	 * Gets an array of Prompt objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Objective has previously been saved, it will retrieve
	 * related Prompts from storage. If this Objective is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Prompt[]
	 * @throws     PropelException
	 */
	public function getPrompts($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ObjectivePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPrompts === null) {
			if ($this->isNew()) {
			   $this->collPrompts = array();
			} else {

				$criteria->add(PromptPeer::OBJECTIVE_ID, $this->id);

				PromptPeer::addSelectColumns($criteria);
				$this->collPrompts = PromptPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(PromptPeer::OBJECTIVE_ID, $this->id);

				PromptPeer::addSelectColumns($criteria);
				if (!isset($this->lastPromptCriteria) || !$this->lastPromptCriteria->equals($criteria)) {
					$this->collPrompts = PromptPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastPromptCriteria = $criteria;
		return $this->collPrompts;
	}

	/**
	 * Returns the number of related Prompt objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Prompt objects.
	 * @throws     PropelException
	 */
	public function countPrompts(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ObjectivePeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collPrompts === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(PromptPeer::OBJECTIVE_ID, $this->id);

				$count = PromptPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(PromptPeer::OBJECTIVE_ID, $this->id);

				if (!isset($this->lastPromptCriteria) || !$this->lastPromptCriteria->equals($criteria)) {
					$count = PromptPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collPrompts);
				}
			} else {
				$count = count($this->collPrompts);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Prompt object to this object
	 * through the Prompt foreign key attribute.
	 *
	 * @param      Prompt $l Prompt
	 * @return     void
	 * @throws     PropelException
	 */
	public function addPrompt(Prompt $l)
	{
		if ($this->collPrompts === null) {
			$this->initPrompts();
		}
		if (!in_array($l, $this->collPrompts, true)) { // only add it if the **same** object is not already associated
			array_push($this->collPrompts, $l);
			$l->setObjective($this);
		}
	}

	/**
	 * Clears out the collEntryConcerns collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addEntryConcerns()
	 */
	public function clearEntryConcerns()
	{
		$this->collEntryConcerns = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collEntryConcerns collection (array).
	 *
	 * By default this just sets the collEntryConcerns collection to an empty array (like clearcollEntryConcerns());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initEntryConcerns()
	{
		$this->collEntryConcerns = array();
	}

	/**
	 * Gets an array of EntryConcern objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Objective has previously been saved, it will retrieve
	 * related EntryConcerns from storage. If this Objective is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array EntryConcern[]
	 * @throws     PropelException
	 */
	public function getEntryConcerns($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ObjectivePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collEntryConcerns === null) {
			if ($this->isNew()) {
			   $this->collEntryConcerns = array();
			} else {

				$criteria->add(EntryConcernPeer::OBJECTIVE_ID, $this->id);

				EntryConcernPeer::addSelectColumns($criteria);
				$this->collEntryConcerns = EntryConcernPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(EntryConcernPeer::OBJECTIVE_ID, $this->id);

				EntryConcernPeer::addSelectColumns($criteria);
				if (!isset($this->lastEntryConcernCriteria) || !$this->lastEntryConcernCriteria->equals($criteria)) {
					$this->collEntryConcerns = EntryConcernPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastEntryConcernCriteria = $criteria;
		return $this->collEntryConcerns;
	}

	/**
	 * Returns the number of related EntryConcern objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related EntryConcern objects.
	 * @throws     PropelException
	 */
	public function countEntryConcerns(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ObjectivePeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collEntryConcerns === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(EntryConcernPeer::OBJECTIVE_ID, $this->id);

				$count = EntryConcernPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(EntryConcernPeer::OBJECTIVE_ID, $this->id);

				if (!isset($this->lastEntryConcernCriteria) || !$this->lastEntryConcernCriteria->equals($criteria)) {
					$count = EntryConcernPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collEntryConcerns);
				}
			} else {
				$count = count($this->collEntryConcerns);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a EntryConcern object to this object
	 * through the EntryConcern foreign key attribute.
	 *
	 * @param      EntryConcern $l EntryConcern
	 * @return     void
	 * @throws     PropelException
	 */
	public function addEntryConcern(EntryConcern $l)
	{
		if ($this->collEntryConcerns === null) {
			$this->initEntryConcerns();
		}
		if (!in_array($l, $this->collEntryConcerns, true)) { // only add it if the **same** object is not already associated
			array_push($this->collEntryConcerns, $l);
			$l->setObjective($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Objective is new, it will return
	 * an empty collection; or if this Objective has previously
	 * been saved, it will retrieve related EntryConcerns from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Objective.
	 */
	public function getEntryConcernsJoinNoteEntry($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ObjectivePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collEntryConcerns === null) {
			if ($this->isNew()) {
				$this->collEntryConcerns = array();
			} else {

				$criteria->add(EntryConcernPeer::OBJECTIVE_ID, $this->id);

				$this->collEntryConcerns = EntryConcernPeer::doSelectJoinNoteEntry($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(EntryConcernPeer::OBJECTIVE_ID, $this->id);

			if (!isset($this->lastEntryConcernCriteria) || !$this->lastEntryConcernCriteria->equals($criteria)) {
				$this->collEntryConcerns = EntryConcernPeer::doSelectJoinNoteEntry($criteria, $con, $join_behavior);
			}
		}
		$this->lastEntryConcernCriteria = $criteria;

		return $this->collEntryConcerns;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Objective is new, it will return
	 * an empty collection; or if this Objective has previously
	 * been saved, it will retrieve related EntryConcerns from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Objective.
	 */
	public function getEntryConcernsJoinAreaOfConcern($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ObjectivePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collEntryConcerns === null) {
			if ($this->isNew()) {
				$this->collEntryConcerns = array();
			} else {

				$criteria->add(EntryConcernPeer::OBJECTIVE_ID, $this->id);

				$this->collEntryConcerns = EntryConcernPeer::doSelectJoinAreaOfConcern($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(EntryConcernPeer::OBJECTIVE_ID, $this->id);

			if (!isset($this->lastEntryConcernCriteria) || !$this->lastEntryConcernCriteria->equals($criteria)) {
				$this->collEntryConcerns = EntryConcernPeer::doSelectJoinAreaOfConcern($criteria, $con, $join_behavior);
			}
		}
		$this->lastEntryConcernCriteria = $criteria;

		return $this->collEntryConcerns;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Objective is new, it will return
	 * an empty collection; or if this Objective has previously
	 * been saved, it will retrieve related EntryConcerns from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Objective.
	 */
	public function getEntryConcernsJoinPrompt($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ObjectivePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collEntryConcerns === null) {
			if ($this->isNew()) {
				$this->collEntryConcerns = array();
			} else {

				$criteria->add(EntryConcernPeer::OBJECTIVE_ID, $this->id);

				$this->collEntryConcerns = EntryConcernPeer::doSelectJoinPrompt($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(EntryConcernPeer::OBJECTIVE_ID, $this->id);

			if (!isset($this->lastEntryConcernCriteria) || !$this->lastEntryConcernCriteria->equals($criteria)) {
				$this->collEntryConcerns = EntryConcernPeer::doSelectJoinPrompt($criteria, $con, $join_behavior);
			}
		}
		$this->lastEntryConcernCriteria = $criteria;

		return $this->collEntryConcerns;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Objective is new, it will return
	 * an empty collection; or if this Objective has previously
	 * been saved, it will retrieve related EntryConcerns from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Objective.
	 */
	public function getEntryConcernsJoinLevel($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ObjectivePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collEntryConcerns === null) {
			if ($this->isNew()) {
				$this->collEntryConcerns = array();
			} else {

				$criteria->add(EntryConcernPeer::OBJECTIVE_ID, $this->id);

				$this->collEntryConcerns = EntryConcernPeer::doSelectJoinLevel($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(EntryConcernPeer::OBJECTIVE_ID, $this->id);

			if (!isset($this->lastEntryConcernCriteria) || !$this->lastEntryConcernCriteria->equals($criteria)) {
				$this->collEntryConcerns = EntryConcernPeer::doSelectJoinLevel($criteria, $con, $join_behavior);
			}
		}
		$this->lastEntryConcernCriteria = $criteria;

		return $this->collEntryConcerns;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collPrompts) {
				foreach ((array) $this->collPrompts as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collEntryConcerns) {
				foreach ((array) $this->collEntryConcerns as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collPrompts = null;
		$this->collEntryConcerns = null;
			$this->aAreaOfConcern = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseObjective:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseObjective::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseObjective
