<?php

/**
 * Base static class for performing query and update operations on the 'note_entry' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Tue Mar 29 20:17:55 2011
 *
 * @package    lib.model.om
 */
abstract class BaseNoteEntryPeer {

	/** the default database name for this class */
	const DATABASE_NAME = 'propel';

	/** the table name for this class */
	const TABLE_NAME = 'note_entry';

	/** A class that can be returned by this peer. */
	const CLASS_DEFAULT = 'lib.model.NoteEntry';

	/** The total number of columns. */
	const NUM_COLUMNS = 15;

	/** The number of lazy-loaded columns. */
	const NUM_LAZY_LOAD_COLUMNS = 0;

	/** the column name for the ID field */
	const ID = 'note_entry.ID';

	/** the column name for the EMPLOYEE_ID field */
	const EMPLOYEE_ID = 'note_entry.EMPLOYEE_ID';

	/** the column name for the CLIENT_ID field */
	const CLIENT_ID = 'note_entry.CLIENT_ID';

	/** the column name for the CLIENT_SERVICE_ID field */
	const CLIENT_SERVICE_ID = 'note_entry.CLIENT_SERVICE_ID';

	/** the column name for the OFFICE_ID field */
	const OFFICE_ID = 'note_entry.OFFICE_ID';

	/** the column name for the FREQUENCY_ID field */
	const FREQUENCY_ID = 'note_entry.FREQUENCY_ID';

	/** the column name for the SERVICE_DATE field */
	const SERVICE_DATE = 'note_entry.SERVICE_DATE';

	/** the column name for the TIME_IN field */
	const TIME_IN = 'note_entry.TIME_IN';

	/** the column name for the TIME_OUT field */
	const TIME_OUT = 'note_entry.TIME_OUT';

	/** the column name for the CPT_CODE field */
	const CPT_CODE = 'note_entry.CPT_CODE';

	/** the column name for the UNITS field */
	const UNITS = 'note_entry.UNITS';

	/** the column name for the ABSENT field */
	const ABSENT = 'note_entry.ABSENT';

	/** the column name for the COMMENTS field */
	const COMMENTS = 'note_entry.COMMENTS';

	/** the column name for the CREATED_AT field */
	const CREATED_AT = 'note_entry.CREATED_AT';

	/** the column name for the UPDATED_AT field */
	const UPDATED_AT = 'note_entry.UPDATED_AT';

	/**
	 * An identiy map to hold any loaded instances of NoteEntry objects.
	 * This must be public so that other peer classes can access this when hydrating from JOIN
	 * queries.
	 * @var        array NoteEntry[]
	 */
	public static $instances = array();

	/**
	 * The MapBuilder instance for this peer.
	 * @var        MapBuilder
	 */
	private static $mapBuilder = null;

	/**
	 * holds an array of fieldnames
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[self::TYPE_PHPNAME][0] = 'Id'
	 */
	private static $fieldNames = array (
		BasePeer::TYPE_PHPNAME => array ('Id', 'EmployeeId', 'ClientId', 'ClientServiceId', 'OfficeId', 'FrequencyId', 'ServiceDate', 'TimeIn', 'TimeOut', 'CptCode', 'Units', 'Absent', 'Comments', 'CreatedAt', 'UpdatedAt', ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id', 'employeeId', 'clientId', 'clientServiceId', 'officeId', 'frequencyId', 'serviceDate', 'timeIn', 'timeOut', 'cptCode', 'units', 'absent', 'comments', 'createdAt', 'updatedAt', ),
		BasePeer::TYPE_COLNAME => array (self::ID, self::EMPLOYEE_ID, self::CLIENT_ID, self::CLIENT_SERVICE_ID, self::OFFICE_ID, self::FREQUENCY_ID, self::SERVICE_DATE, self::TIME_IN, self::TIME_OUT, self::CPT_CODE, self::UNITS, self::ABSENT, self::COMMENTS, self::CREATED_AT, self::UPDATED_AT, ),
		BasePeer::TYPE_FIELDNAME => array ('id', 'employee_id', 'client_id', 'client_service_id', 'office_id', 'frequency_id', 'service_date', 'time_in', 'time_out', 'cpt_code', 'units', 'absent', 'comments', 'created_at', 'updated_at', ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, )
	);

	/**
	 * holds an array of keys for quick access to the fieldnames array
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
	 */
	private static $fieldKeys = array (
		BasePeer::TYPE_PHPNAME => array ('Id' => 0, 'EmployeeId' => 1, 'ClientId' => 2, 'ClientServiceId' => 3, 'OfficeId' => 4, 'FrequencyId' => 5, 'ServiceDate' => 6, 'TimeIn' => 7, 'TimeOut' => 8, 'CptCode' => 9, 'Units' => 10, 'Absent' => 11, 'Comments' => 12, 'CreatedAt' => 13, 'UpdatedAt' => 14, ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id' => 0, 'employeeId' => 1, 'clientId' => 2, 'clientServiceId' => 3, 'officeId' => 4, 'frequencyId' => 5, 'serviceDate' => 6, 'timeIn' => 7, 'timeOut' => 8, 'cptCode' => 9, 'units' => 10, 'absent' => 11, 'comments' => 12, 'createdAt' => 13, 'updatedAt' => 14, ),
		BasePeer::TYPE_COLNAME => array (self::ID => 0, self::EMPLOYEE_ID => 1, self::CLIENT_ID => 2, self::CLIENT_SERVICE_ID => 3, self::OFFICE_ID => 4, self::FREQUENCY_ID => 5, self::SERVICE_DATE => 6, self::TIME_IN => 7, self::TIME_OUT => 8, self::CPT_CODE => 9, self::UNITS => 10, self::ABSENT => 11, self::COMMENTS => 12, self::CREATED_AT => 13, self::UPDATED_AT => 14, ),
		BasePeer::TYPE_FIELDNAME => array ('id' => 0, 'employee_id' => 1, 'client_id' => 2, 'client_service_id' => 3, 'office_id' => 4, 'frequency_id' => 5, 'service_date' => 6, 'time_in' => 7, 'time_out' => 8, 'cpt_code' => 9, 'units' => 10, 'absent' => 11, 'comments' => 12, 'created_at' => 13, 'updated_at' => 14, ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, )
	);

	/**
	 * Get a (singleton) instance of the MapBuilder for this peer class.
	 * @return     MapBuilder The map builder for this peer
	 */
	public static function getMapBuilder()
	{
		if (self::$mapBuilder === null) {
			self::$mapBuilder = new NoteEntryMapBuilder();
		}
		return self::$mapBuilder;
	}
	/**
	 * Translates a fieldname to another type
	 *
	 * @param      string $name field name
	 * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @param      string $toType   One of the class type constants
	 * @return     string translated name of the field.
	 * @throws     PropelException - if the specified name could not be found in the fieldname mappings.
	 */
	static public function translateFieldName($name, $fromType, $toType)
	{
		$toNames = self::getFieldNames($toType);
		$key = isset(self::$fieldKeys[$fromType][$name]) ? self::$fieldKeys[$fromType][$name] : null;
		if ($key === null) {
			throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(self::$fieldKeys[$fromType], true));
		}
		return $toNames[$key];
	}

	/**
	 * Returns an array of field names.
	 *
	 * @param      string $type The type of fieldnames to return:
	 *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     array A list of field names
	 */

	static public function getFieldNames($type = BasePeer::TYPE_PHPNAME)
	{
		if (!array_key_exists($type, self::$fieldNames)) {
			throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
		}
		return self::$fieldNames[$type];
	}

	/**
	 * Convenience method which changes table.column to alias.column.
	 *
	 * Using this method you can maintain SQL abstraction while using column aliases.
	 * <code>
	 *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
	 *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
	 * </code>
	 * @param      string $alias The alias for the current table.
	 * @param      string $column The column name for current table. (i.e. NoteEntryPeer::COLUMN_NAME).
	 * @return     string
	 */
	public static function alias($alias, $column)
	{
		return str_replace(NoteEntryPeer::TABLE_NAME.'.', $alias.'.', $column);
	}

	/**
	 * Add all the columns needed to create a new object.
	 *
	 * Note: any columns that were marked with lazyLoad="true" in the
	 * XML schema will not be added to the select list and only loaded
	 * on demand.
	 *
	 * @param      criteria object containing the columns to add.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function addSelectColumns(Criteria $criteria)
	{

		$criteria->addSelectColumn(NoteEntryPeer::ID);

		$criteria->addSelectColumn(NoteEntryPeer::EMPLOYEE_ID);

		$criteria->addSelectColumn(NoteEntryPeer::CLIENT_ID);

		$criteria->addSelectColumn(NoteEntryPeer::CLIENT_SERVICE_ID);

		$criteria->addSelectColumn(NoteEntryPeer::OFFICE_ID);

		$criteria->addSelectColumn(NoteEntryPeer::FREQUENCY_ID);

		$criteria->addSelectColumn(NoteEntryPeer::SERVICE_DATE);

		$criteria->addSelectColumn(NoteEntryPeer::TIME_IN);

		$criteria->addSelectColumn(NoteEntryPeer::TIME_OUT);

		$criteria->addSelectColumn(NoteEntryPeer::CPT_CODE);

		$criteria->addSelectColumn(NoteEntryPeer::UNITS);

		$criteria->addSelectColumn(NoteEntryPeer::ABSENT);

		$criteria->addSelectColumn(NoteEntryPeer::COMMENTS);

		$criteria->addSelectColumn(NoteEntryPeer::CREATED_AT);

		$criteria->addSelectColumn(NoteEntryPeer::UPDATED_AT);

	}

	/**
	 * Returns the number of rows matching criteria.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @return     int Number of matching rows.
	 */
	public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
	{
		// we may modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(NoteEntryPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			NoteEntryPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		$criteria->setDbName(self::DATABASE_NAME); // Set the correct dbName

		if ($con === null) {
			$con = Propel::getConnection(NoteEntryPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}


    foreach (sfMixer::getCallables('BaseNoteEntryPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseNoteEntryPeer', $criteria, $con);
    }


		// BasePeer returns a PDOStatement
		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}
	/**
	 * Method to select one object from the DB.
	 *
	 * @param      Criteria $criteria object used to create the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     NoteEntry
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
	{
		$critcopy = clone $criteria;
		$critcopy->setLimit(1);
		$objects = NoteEntryPeer::doSelect($critcopy, $con);
		if ($objects) {
			return $objects[0];
		}
		return null;
	}
	/**
	 * Method to do selects.
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     array Array of selected Objects
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelect(Criteria $criteria, PropelPDO $con = null)
	{
		return NoteEntryPeer::populateObjects(NoteEntryPeer::doSelectStmt($criteria, $con));
	}
	/**
	 * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
	 *
	 * Use this method directly if you want to work with an executed statement durirectly (for example
	 * to perform your own object hydration).
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con The connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     PDOStatement The executed PDOStatement object.
	 * @see        BasePeer::doSelect()
	 */
	public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseNoteEntryPeer:doSelectStmt:doSelectStmt') as $callable)
    {
      call_user_func($callable, 'BaseNoteEntryPeer', $criteria, $con);
    }


		if ($con === null) {
			$con = Propel::getConnection(NoteEntryPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		if (!$criteria->hasSelectClause()) {
			$criteria = clone $criteria;
			NoteEntryPeer::addSelectColumns($criteria);
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		// BasePeer returns a PDOStatement
		return BasePeer::doSelect($criteria, $con);
	}
	/**
	 * Adds an object to the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doSelect*()
	 * methods in your stub classes -- you may need to explicitly add objects
	 * to the cache in order to ensure that the same objects are always returned by doSelect*()
	 * and retrieveByPK*() calls.
	 *
	 * @param      NoteEntry $value A NoteEntry object.
	 * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
	 */
	public static function addInstanceToPool(NoteEntry $obj, $key = null)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if ($key === null) {
				$key = (string) $obj->getId();
			} // if key === null
			self::$instances[$key] = $obj;
		}
	}

	/**
	 * Removes an object from the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doDelete
	 * methods in your stub classes -- you may need to explicitly remove objects
	 * from the cache in order to prevent returning objects that no longer exist.
	 *
	 * @param      mixed $value A NoteEntry object or a primary key value.
	 */
	public static function removeInstanceFromPool($value)
	{
		if (Propel::isInstancePoolingEnabled() && $value !== null) {
			if (is_object($value) && $value instanceof NoteEntry) {
				$key = (string) $value->getId();
			} elseif (is_scalar($value)) {
				// assume we've been passed a primary key
				$key = (string) $value;
			} else {
				$e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or NoteEntry object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
				throw $e;
			}

			unset(self::$instances[$key]);
		}
	} // removeInstanceFromPool()

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
	 * @return     NoteEntry Found object or NULL if 1) no instance exists for specified key or 2) instance pooling has been disabled.
	 * @see        getPrimaryKeyHash()
	 */
	public static function getInstanceFromPool($key)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if (isset(self::$instances[$key])) {
				return self::$instances[$key];
			}
		}
		return null; // just to be explicit
	}
	
	/**
	 * Clear the instance pool.
	 *
	 * @return     void
	 */
	public static function clearInstancePool()
	{
		self::$instances = array();
	}
	
	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     string A string version of PK or NULL if the components of primary key in result array are all null.
	 */
	public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
	{
		// If the PK cannot be derived from the row, return NULL.
		if ($row[$startcol + 0] === null) {
			return null;
		}
		return (string) $row[$startcol + 0];
	}

	/**
	 * The returned array will contain objects of the default type or
	 * objects that inherit from the default.
	 *
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function populateObjects(PDOStatement $stmt)
	{
		$results = array();
	
		// set the class once to avoid overhead in the loop
		$cls = NoteEntryPeer::getOMClass();
		$cls = substr('.'.$cls, strrpos('.'.$cls, '.') + 1);
		// populate the object(s)
		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key = NoteEntryPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj = NoteEntryPeer::getInstanceFromPool($key))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj->hydrate($row, 0, true); // rehydrate
				$results[] = $obj;
			} else {
		
				$obj = new $cls();
				$obj->hydrate($row);
				$results[] = $obj;
				NoteEntryPeer::addInstanceToPool($obj, $key);
			} // if key exists
		}
		$stmt->closeCursor();
		return $results;
	}

	/**
	 * Returns the number of rows matching criteria, joining the related Employee table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinEmployee(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(NoteEntryPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			NoteEntryPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(NoteEntryPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(NoteEntryPeer::EMPLOYEE_ID,), array(EmployeePeer::ID,), $join_behavior);


    foreach (sfMixer::getCallables('BaseNoteEntryPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseNoteEntryPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Client table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinClient(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(NoteEntryPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			NoteEntryPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(NoteEntryPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(NoteEntryPeer::CLIENT_ID,), array(ClientPeer::ID,), $join_behavior);


    foreach (sfMixer::getCallables('BaseNoteEntryPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseNoteEntryPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related ClientService table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinClientService(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(NoteEntryPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			NoteEntryPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(NoteEntryPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(NoteEntryPeer::CLIENT_SERVICE_ID,), array(ClientServicePeer::ID,), $join_behavior);


    foreach (sfMixer::getCallables('BaseNoteEntryPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseNoteEntryPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Office table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinOffice(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(NoteEntryPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			NoteEntryPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(NoteEntryPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(NoteEntryPeer::OFFICE_ID,), array(OfficePeer::ID,), $join_behavior);


    foreach (sfMixer::getCallables('BaseNoteEntryPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseNoteEntryPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Frequency table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinFrequency(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(NoteEntryPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			NoteEntryPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(NoteEntryPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(NoteEntryPeer::FREQUENCY_ID,), array(FrequencyPeer::ID,), $join_behavior);


    foreach (sfMixer::getCallables('BaseNoteEntryPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseNoteEntryPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Selects a collection of NoteEntry objects pre-filled with their Employee objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of NoteEntry objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinEmployee(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{

    foreach (sfMixer::getCallables('BaseNoteEntryPeer:doSelectJoin:doSelectJoin') as $callable)
    {
      call_user_func($callable, 'BaseNoteEntryPeer', $c, $con);
    }


		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		NoteEntryPeer::addSelectColumns($c);
		$startcol = (NoteEntryPeer::NUM_COLUMNS - NoteEntryPeer::NUM_LAZY_LOAD_COLUMNS);
		EmployeePeer::addSelectColumns($c);

		$c->addJoin(array(NoteEntryPeer::EMPLOYEE_ID,), array(EmployeePeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = NoteEntryPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = NoteEntryPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = NoteEntryPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				NoteEntryPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = EmployeePeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = EmployeePeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = EmployeePeer::getOMClass();

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					EmployeePeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (NoteEntry) to $obj2 (Employee)
				$obj2->addNoteEntry($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of NoteEntry objects pre-filled with their Client objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of NoteEntry objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinClient(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		NoteEntryPeer::addSelectColumns($c);
		$startcol = (NoteEntryPeer::NUM_COLUMNS - NoteEntryPeer::NUM_LAZY_LOAD_COLUMNS);
		ClientPeer::addSelectColumns($c);

		$c->addJoin(array(NoteEntryPeer::CLIENT_ID,), array(ClientPeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = NoteEntryPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = NoteEntryPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = NoteEntryPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				NoteEntryPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = ClientPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = ClientPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = ClientPeer::getOMClass();

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					ClientPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (NoteEntry) to $obj2 (Client)
				$obj2->addNoteEntry($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of NoteEntry objects pre-filled with their ClientService objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of NoteEntry objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinClientService(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		NoteEntryPeer::addSelectColumns($c);
		$startcol = (NoteEntryPeer::NUM_COLUMNS - NoteEntryPeer::NUM_LAZY_LOAD_COLUMNS);
		ClientServicePeer::addSelectColumns($c);

		$c->addJoin(array(NoteEntryPeer::CLIENT_SERVICE_ID,), array(ClientServicePeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = NoteEntryPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = NoteEntryPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = NoteEntryPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				NoteEntryPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = ClientServicePeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = ClientServicePeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = ClientServicePeer::getOMClass($row, $startcol);

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					ClientServicePeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (NoteEntry) to $obj2 (ClientService)
				$obj2->addNoteEntry($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of NoteEntry objects pre-filled with their Office objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of NoteEntry objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinOffice(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		NoteEntryPeer::addSelectColumns($c);
		$startcol = (NoteEntryPeer::NUM_COLUMNS - NoteEntryPeer::NUM_LAZY_LOAD_COLUMNS);
		OfficePeer::addSelectColumns($c);

		$c->addJoin(array(NoteEntryPeer::OFFICE_ID,), array(OfficePeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = NoteEntryPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = NoteEntryPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = NoteEntryPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				NoteEntryPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = OfficePeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = OfficePeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = OfficePeer::getOMClass();

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					OfficePeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (NoteEntry) to $obj2 (Office)
				$obj2->addNoteEntry($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of NoteEntry objects pre-filled with their Frequency objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of NoteEntry objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinFrequency(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		NoteEntryPeer::addSelectColumns($c);
		$startcol = (NoteEntryPeer::NUM_COLUMNS - NoteEntryPeer::NUM_LAZY_LOAD_COLUMNS);
		FrequencyPeer::addSelectColumns($c);

		$c->addJoin(array(NoteEntryPeer::FREQUENCY_ID,), array(FrequencyPeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = NoteEntryPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = NoteEntryPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = NoteEntryPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				NoteEntryPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = FrequencyPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = FrequencyPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = FrequencyPeer::getOMClass();

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					FrequencyPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (NoteEntry) to $obj2 (Frequency)
				$obj2->addNoteEntry($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Returns the number of rows matching criteria, joining all related tables
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAll(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(NoteEntryPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			NoteEntryPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(NoteEntryPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(NoteEntryPeer::EMPLOYEE_ID,), array(EmployeePeer::ID,), $join_behavior);
		$criteria->addJoin(array(NoteEntryPeer::CLIENT_ID,), array(ClientPeer::ID,), $join_behavior);
		$criteria->addJoin(array(NoteEntryPeer::CLIENT_SERVICE_ID,), array(ClientServicePeer::ID,), $join_behavior);
		$criteria->addJoin(array(NoteEntryPeer::OFFICE_ID,), array(OfficePeer::ID,), $join_behavior);
		$criteria->addJoin(array(NoteEntryPeer::FREQUENCY_ID,), array(FrequencyPeer::ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseNoteEntryPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseNoteEntryPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}

	/**
	 * Selects a collection of NoteEntry objects pre-filled with all related objects.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of NoteEntry objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAll(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{

    foreach (sfMixer::getCallables('BaseNoteEntryPeer:doSelectJoinAll:doSelectJoinAll') as $callable)
    {
      call_user_func($callable, 'BaseNoteEntryPeer', $c, $con);
    }


		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		NoteEntryPeer::addSelectColumns($c);
		$startcol2 = (NoteEntryPeer::NUM_COLUMNS - NoteEntryPeer::NUM_LAZY_LOAD_COLUMNS);

		EmployeePeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (EmployeePeer::NUM_COLUMNS - EmployeePeer::NUM_LAZY_LOAD_COLUMNS);

		ClientPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (ClientPeer::NUM_COLUMNS - ClientPeer::NUM_LAZY_LOAD_COLUMNS);

		ClientServicePeer::addSelectColumns($c);
		$startcol5 = $startcol4 + (ClientServicePeer::NUM_COLUMNS - ClientServicePeer::NUM_LAZY_LOAD_COLUMNS);

		OfficePeer::addSelectColumns($c);
		$startcol6 = $startcol5 + (OfficePeer::NUM_COLUMNS - OfficePeer::NUM_LAZY_LOAD_COLUMNS);

		FrequencyPeer::addSelectColumns($c);
		$startcol7 = $startcol6 + (FrequencyPeer::NUM_COLUMNS - FrequencyPeer::NUM_LAZY_LOAD_COLUMNS);

		$c->addJoin(array(NoteEntryPeer::EMPLOYEE_ID,), array(EmployeePeer::ID,), $join_behavior);
		$c->addJoin(array(NoteEntryPeer::CLIENT_ID,), array(ClientPeer::ID,), $join_behavior);
		$c->addJoin(array(NoteEntryPeer::CLIENT_SERVICE_ID,), array(ClientServicePeer::ID,), $join_behavior);
		$c->addJoin(array(NoteEntryPeer::OFFICE_ID,), array(OfficePeer::ID,), $join_behavior);
		$c->addJoin(array(NoteEntryPeer::FREQUENCY_ID,), array(FrequencyPeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = NoteEntryPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = NoteEntryPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = NoteEntryPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				NoteEntryPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

			// Add objects for joined Employee rows

			$key2 = EmployeePeer::getPrimaryKeyHashFromRow($row, $startcol2);
			if ($key2 !== null) {
				$obj2 = EmployeePeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = EmployeePeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					EmployeePeer::addInstanceToPool($obj2, $key2);
				} // if obj2 loaded

				// Add the $obj1 (NoteEntry) to the collection in $obj2 (Employee)
				$obj2->addNoteEntry($obj1);
			} // if joined row not null

			// Add objects for joined Client rows

			$key3 = ClientPeer::getPrimaryKeyHashFromRow($row, $startcol3);
			if ($key3 !== null) {
				$obj3 = ClientPeer::getInstanceFromPool($key3);
				if (!$obj3) {

					$omClass = ClientPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					ClientPeer::addInstanceToPool($obj3, $key3);
				} // if obj3 loaded

				// Add the $obj1 (NoteEntry) to the collection in $obj3 (Client)
				$obj3->addNoteEntry($obj1);
			} // if joined row not null

			// Add objects for joined ClientService rows

			$key4 = ClientServicePeer::getPrimaryKeyHashFromRow($row, $startcol4);
			if ($key4 !== null) {
				$obj4 = ClientServicePeer::getInstanceFromPool($key4);
				if (!$obj4) {

					$omClass = ClientServicePeer::getOMClass($row, $startcol4);


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					ClientServicePeer::addInstanceToPool($obj4, $key4);
				} // if obj4 loaded

				// Add the $obj1 (NoteEntry) to the collection in $obj4 (ClientService)
				$obj4->addNoteEntry($obj1);
			} // if joined row not null

			// Add objects for joined Office rows

			$key5 = OfficePeer::getPrimaryKeyHashFromRow($row, $startcol5);
			if ($key5 !== null) {
				$obj5 = OfficePeer::getInstanceFromPool($key5);
				if (!$obj5) {

					$omClass = OfficePeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj5 = new $cls();
					$obj5->hydrate($row, $startcol5);
					OfficePeer::addInstanceToPool($obj5, $key5);
				} // if obj5 loaded

				// Add the $obj1 (NoteEntry) to the collection in $obj5 (Office)
				$obj5->addNoteEntry($obj1);
			} // if joined row not null

			// Add objects for joined Frequency rows

			$key6 = FrequencyPeer::getPrimaryKeyHashFromRow($row, $startcol6);
			if ($key6 !== null) {
				$obj6 = FrequencyPeer::getInstanceFromPool($key6);
				if (!$obj6) {

					$omClass = FrequencyPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj6 = new $cls();
					$obj6->hydrate($row, $startcol6);
					FrequencyPeer::addInstanceToPool($obj6, $key6);
				} // if obj6 loaded

				// Add the $obj1 (NoteEntry) to the collection in $obj6 (Frequency)
				$obj6->addNoteEntry($obj1);
			} // if joined row not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Employee table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptEmployee(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			NoteEntryPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(NoteEntryPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(NoteEntryPeer::CLIENT_ID,), array(ClientPeer::ID,), $join_behavior);
				$criteria->addJoin(array(NoteEntryPeer::CLIENT_SERVICE_ID,), array(ClientServicePeer::ID,), $join_behavior);
				$criteria->addJoin(array(NoteEntryPeer::OFFICE_ID,), array(OfficePeer::ID,), $join_behavior);
				$criteria->addJoin(array(NoteEntryPeer::FREQUENCY_ID,), array(FrequencyPeer::ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseNoteEntryPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseNoteEntryPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Client table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptClient(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			NoteEntryPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(NoteEntryPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(NoteEntryPeer::EMPLOYEE_ID,), array(EmployeePeer::ID,), $join_behavior);
				$criteria->addJoin(array(NoteEntryPeer::CLIENT_SERVICE_ID,), array(ClientServicePeer::ID,), $join_behavior);
				$criteria->addJoin(array(NoteEntryPeer::OFFICE_ID,), array(OfficePeer::ID,), $join_behavior);
				$criteria->addJoin(array(NoteEntryPeer::FREQUENCY_ID,), array(FrequencyPeer::ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseNoteEntryPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseNoteEntryPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related ClientService table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptClientService(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			NoteEntryPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(NoteEntryPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(NoteEntryPeer::EMPLOYEE_ID,), array(EmployeePeer::ID,), $join_behavior);
				$criteria->addJoin(array(NoteEntryPeer::CLIENT_ID,), array(ClientPeer::ID,), $join_behavior);
				$criteria->addJoin(array(NoteEntryPeer::OFFICE_ID,), array(OfficePeer::ID,), $join_behavior);
				$criteria->addJoin(array(NoteEntryPeer::FREQUENCY_ID,), array(FrequencyPeer::ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseNoteEntryPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseNoteEntryPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Office table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptOffice(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			NoteEntryPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(NoteEntryPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(NoteEntryPeer::EMPLOYEE_ID,), array(EmployeePeer::ID,), $join_behavior);
				$criteria->addJoin(array(NoteEntryPeer::CLIENT_ID,), array(ClientPeer::ID,), $join_behavior);
				$criteria->addJoin(array(NoteEntryPeer::CLIENT_SERVICE_ID,), array(ClientServicePeer::ID,), $join_behavior);
				$criteria->addJoin(array(NoteEntryPeer::FREQUENCY_ID,), array(FrequencyPeer::ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseNoteEntryPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseNoteEntryPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Frequency table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptFrequency(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			NoteEntryPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(NoteEntryPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(NoteEntryPeer::EMPLOYEE_ID,), array(EmployeePeer::ID,), $join_behavior);
				$criteria->addJoin(array(NoteEntryPeer::CLIENT_ID,), array(ClientPeer::ID,), $join_behavior);
				$criteria->addJoin(array(NoteEntryPeer::CLIENT_SERVICE_ID,), array(ClientServicePeer::ID,), $join_behavior);
				$criteria->addJoin(array(NoteEntryPeer::OFFICE_ID,), array(OfficePeer::ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseNoteEntryPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseNoteEntryPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Selects a collection of NoteEntry objects pre-filled with all related objects except Employee.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of NoteEntry objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptEmployee(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{

    foreach (sfMixer::getCallables('BaseNoteEntryPeer:doSelectJoinAllExcept:doSelectJoinAllExcept') as $callable)
    {
      call_user_func($callable, 'BaseNoteEntryPeer', $c, $con);
    }


		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		NoteEntryPeer::addSelectColumns($c);
		$startcol2 = (NoteEntryPeer::NUM_COLUMNS - NoteEntryPeer::NUM_LAZY_LOAD_COLUMNS);

		ClientPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (ClientPeer::NUM_COLUMNS - ClientPeer::NUM_LAZY_LOAD_COLUMNS);

		ClientServicePeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (ClientServicePeer::NUM_COLUMNS - ClientServicePeer::NUM_LAZY_LOAD_COLUMNS);

		OfficePeer::addSelectColumns($c);
		$startcol5 = $startcol4 + (OfficePeer::NUM_COLUMNS - OfficePeer::NUM_LAZY_LOAD_COLUMNS);

		FrequencyPeer::addSelectColumns($c);
		$startcol6 = $startcol5 + (FrequencyPeer::NUM_COLUMNS - FrequencyPeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(NoteEntryPeer::CLIENT_ID,), array(ClientPeer::ID,), $join_behavior);
				$c->addJoin(array(NoteEntryPeer::CLIENT_SERVICE_ID,), array(ClientServicePeer::ID,), $join_behavior);
				$c->addJoin(array(NoteEntryPeer::OFFICE_ID,), array(OfficePeer::ID,), $join_behavior);
				$c->addJoin(array(NoteEntryPeer::FREQUENCY_ID,), array(FrequencyPeer::ID,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = NoteEntryPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = NoteEntryPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = NoteEntryPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				NoteEntryPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined Client rows

				$key2 = ClientPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = ClientPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = ClientPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					ClientPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (NoteEntry) to the collection in $obj2 (Client)
				$obj2->addNoteEntry($obj1);

			} // if joined row is not null

				// Add objects for joined ClientService rows

				$key3 = ClientServicePeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = ClientServicePeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$omClass = ClientServicePeer::getOMClass($row, $startcol3);


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					ClientServicePeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (NoteEntry) to the collection in $obj3 (ClientService)
				$obj3->addNoteEntry($obj1);

			} // if joined row is not null

				// Add objects for joined Office rows

				$key4 = OfficePeer::getPrimaryKeyHashFromRow($row, $startcol4);
				if ($key4 !== null) {
					$obj4 = OfficePeer::getInstanceFromPool($key4);
					if (!$obj4) {
	
						$omClass = OfficePeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					OfficePeer::addInstanceToPool($obj4, $key4);
				} // if $obj4 already loaded

				// Add the $obj1 (NoteEntry) to the collection in $obj4 (Office)
				$obj4->addNoteEntry($obj1);

			} // if joined row is not null

				// Add objects for joined Frequency rows

				$key5 = FrequencyPeer::getPrimaryKeyHashFromRow($row, $startcol5);
				if ($key5 !== null) {
					$obj5 = FrequencyPeer::getInstanceFromPool($key5);
					if (!$obj5) {
	
						$omClass = FrequencyPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj5 = new $cls();
					$obj5->hydrate($row, $startcol5);
					FrequencyPeer::addInstanceToPool($obj5, $key5);
				} // if $obj5 already loaded

				// Add the $obj1 (NoteEntry) to the collection in $obj5 (Frequency)
				$obj5->addNoteEntry($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of NoteEntry objects pre-filled with all related objects except Client.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of NoteEntry objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptClient(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		NoteEntryPeer::addSelectColumns($c);
		$startcol2 = (NoteEntryPeer::NUM_COLUMNS - NoteEntryPeer::NUM_LAZY_LOAD_COLUMNS);

		EmployeePeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (EmployeePeer::NUM_COLUMNS - EmployeePeer::NUM_LAZY_LOAD_COLUMNS);

		ClientServicePeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (ClientServicePeer::NUM_COLUMNS - ClientServicePeer::NUM_LAZY_LOAD_COLUMNS);

		OfficePeer::addSelectColumns($c);
		$startcol5 = $startcol4 + (OfficePeer::NUM_COLUMNS - OfficePeer::NUM_LAZY_LOAD_COLUMNS);

		FrequencyPeer::addSelectColumns($c);
		$startcol6 = $startcol5 + (FrequencyPeer::NUM_COLUMNS - FrequencyPeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(NoteEntryPeer::EMPLOYEE_ID,), array(EmployeePeer::ID,), $join_behavior);
				$c->addJoin(array(NoteEntryPeer::CLIENT_SERVICE_ID,), array(ClientServicePeer::ID,), $join_behavior);
				$c->addJoin(array(NoteEntryPeer::OFFICE_ID,), array(OfficePeer::ID,), $join_behavior);
				$c->addJoin(array(NoteEntryPeer::FREQUENCY_ID,), array(FrequencyPeer::ID,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = NoteEntryPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = NoteEntryPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = NoteEntryPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				NoteEntryPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined Employee rows

				$key2 = EmployeePeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = EmployeePeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = EmployeePeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					EmployeePeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (NoteEntry) to the collection in $obj2 (Employee)
				$obj2->addNoteEntry($obj1);

			} // if joined row is not null

				// Add objects for joined ClientService rows

				$key3 = ClientServicePeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = ClientServicePeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$omClass = ClientServicePeer::getOMClass($row, $startcol3);


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					ClientServicePeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (NoteEntry) to the collection in $obj3 (ClientService)
				$obj3->addNoteEntry($obj1);

			} // if joined row is not null

				// Add objects for joined Office rows

				$key4 = OfficePeer::getPrimaryKeyHashFromRow($row, $startcol4);
				if ($key4 !== null) {
					$obj4 = OfficePeer::getInstanceFromPool($key4);
					if (!$obj4) {
	
						$omClass = OfficePeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					OfficePeer::addInstanceToPool($obj4, $key4);
				} // if $obj4 already loaded

				// Add the $obj1 (NoteEntry) to the collection in $obj4 (Office)
				$obj4->addNoteEntry($obj1);

			} // if joined row is not null

				// Add objects for joined Frequency rows

				$key5 = FrequencyPeer::getPrimaryKeyHashFromRow($row, $startcol5);
				if ($key5 !== null) {
					$obj5 = FrequencyPeer::getInstanceFromPool($key5);
					if (!$obj5) {
	
						$omClass = FrequencyPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj5 = new $cls();
					$obj5->hydrate($row, $startcol5);
					FrequencyPeer::addInstanceToPool($obj5, $key5);
				} // if $obj5 already loaded

				// Add the $obj1 (NoteEntry) to the collection in $obj5 (Frequency)
				$obj5->addNoteEntry($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of NoteEntry objects pre-filled with all related objects except ClientService.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of NoteEntry objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptClientService(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		NoteEntryPeer::addSelectColumns($c);
		$startcol2 = (NoteEntryPeer::NUM_COLUMNS - NoteEntryPeer::NUM_LAZY_LOAD_COLUMNS);

		EmployeePeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (EmployeePeer::NUM_COLUMNS - EmployeePeer::NUM_LAZY_LOAD_COLUMNS);

		ClientPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (ClientPeer::NUM_COLUMNS - ClientPeer::NUM_LAZY_LOAD_COLUMNS);

		OfficePeer::addSelectColumns($c);
		$startcol5 = $startcol4 + (OfficePeer::NUM_COLUMNS - OfficePeer::NUM_LAZY_LOAD_COLUMNS);

		FrequencyPeer::addSelectColumns($c);
		$startcol6 = $startcol5 + (FrequencyPeer::NUM_COLUMNS - FrequencyPeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(NoteEntryPeer::EMPLOYEE_ID,), array(EmployeePeer::ID,), $join_behavior);
				$c->addJoin(array(NoteEntryPeer::CLIENT_ID,), array(ClientPeer::ID,), $join_behavior);
				$c->addJoin(array(NoteEntryPeer::OFFICE_ID,), array(OfficePeer::ID,), $join_behavior);
				$c->addJoin(array(NoteEntryPeer::FREQUENCY_ID,), array(FrequencyPeer::ID,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = NoteEntryPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = NoteEntryPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = NoteEntryPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				NoteEntryPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined Employee rows

				$key2 = EmployeePeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = EmployeePeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = EmployeePeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					EmployeePeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (NoteEntry) to the collection in $obj2 (Employee)
				$obj2->addNoteEntry($obj1);

			} // if joined row is not null

				// Add objects for joined Client rows

				$key3 = ClientPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = ClientPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$omClass = ClientPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					ClientPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (NoteEntry) to the collection in $obj3 (Client)
				$obj3->addNoteEntry($obj1);

			} // if joined row is not null

				// Add objects for joined Office rows

				$key4 = OfficePeer::getPrimaryKeyHashFromRow($row, $startcol4);
				if ($key4 !== null) {
					$obj4 = OfficePeer::getInstanceFromPool($key4);
					if (!$obj4) {
	
						$omClass = OfficePeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					OfficePeer::addInstanceToPool($obj4, $key4);
				} // if $obj4 already loaded

				// Add the $obj1 (NoteEntry) to the collection in $obj4 (Office)
				$obj4->addNoteEntry($obj1);

			} // if joined row is not null

				// Add objects for joined Frequency rows

				$key5 = FrequencyPeer::getPrimaryKeyHashFromRow($row, $startcol5);
				if ($key5 !== null) {
					$obj5 = FrequencyPeer::getInstanceFromPool($key5);
					if (!$obj5) {
	
						$omClass = FrequencyPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj5 = new $cls();
					$obj5->hydrate($row, $startcol5);
					FrequencyPeer::addInstanceToPool($obj5, $key5);
				} // if $obj5 already loaded

				// Add the $obj1 (NoteEntry) to the collection in $obj5 (Frequency)
				$obj5->addNoteEntry($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of NoteEntry objects pre-filled with all related objects except Office.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of NoteEntry objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptOffice(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		NoteEntryPeer::addSelectColumns($c);
		$startcol2 = (NoteEntryPeer::NUM_COLUMNS - NoteEntryPeer::NUM_LAZY_LOAD_COLUMNS);

		EmployeePeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (EmployeePeer::NUM_COLUMNS - EmployeePeer::NUM_LAZY_LOAD_COLUMNS);

		ClientPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (ClientPeer::NUM_COLUMNS - ClientPeer::NUM_LAZY_LOAD_COLUMNS);

		ClientServicePeer::addSelectColumns($c);
		$startcol5 = $startcol4 + (ClientServicePeer::NUM_COLUMNS - ClientServicePeer::NUM_LAZY_LOAD_COLUMNS);

		FrequencyPeer::addSelectColumns($c);
		$startcol6 = $startcol5 + (FrequencyPeer::NUM_COLUMNS - FrequencyPeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(NoteEntryPeer::EMPLOYEE_ID,), array(EmployeePeer::ID,), $join_behavior);
				$c->addJoin(array(NoteEntryPeer::CLIENT_ID,), array(ClientPeer::ID,), $join_behavior);
				$c->addJoin(array(NoteEntryPeer::CLIENT_SERVICE_ID,), array(ClientServicePeer::ID,), $join_behavior);
				$c->addJoin(array(NoteEntryPeer::FREQUENCY_ID,), array(FrequencyPeer::ID,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = NoteEntryPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = NoteEntryPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = NoteEntryPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				NoteEntryPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined Employee rows

				$key2 = EmployeePeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = EmployeePeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = EmployeePeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					EmployeePeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (NoteEntry) to the collection in $obj2 (Employee)
				$obj2->addNoteEntry($obj1);

			} // if joined row is not null

				// Add objects for joined Client rows

				$key3 = ClientPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = ClientPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$omClass = ClientPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					ClientPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (NoteEntry) to the collection in $obj3 (Client)
				$obj3->addNoteEntry($obj1);

			} // if joined row is not null

				// Add objects for joined ClientService rows

				$key4 = ClientServicePeer::getPrimaryKeyHashFromRow($row, $startcol4);
				if ($key4 !== null) {
					$obj4 = ClientServicePeer::getInstanceFromPool($key4);
					if (!$obj4) {
	
						$omClass = ClientServicePeer::getOMClass($row, $startcol4);


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					ClientServicePeer::addInstanceToPool($obj4, $key4);
				} // if $obj4 already loaded

				// Add the $obj1 (NoteEntry) to the collection in $obj4 (ClientService)
				$obj4->addNoteEntry($obj1);

			} // if joined row is not null

				// Add objects for joined Frequency rows

				$key5 = FrequencyPeer::getPrimaryKeyHashFromRow($row, $startcol5);
				if ($key5 !== null) {
					$obj5 = FrequencyPeer::getInstanceFromPool($key5);
					if (!$obj5) {
	
						$omClass = FrequencyPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj5 = new $cls();
					$obj5->hydrate($row, $startcol5);
					FrequencyPeer::addInstanceToPool($obj5, $key5);
				} // if $obj5 already loaded

				// Add the $obj1 (NoteEntry) to the collection in $obj5 (Frequency)
				$obj5->addNoteEntry($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of NoteEntry objects pre-filled with all related objects except Frequency.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of NoteEntry objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptFrequency(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		NoteEntryPeer::addSelectColumns($c);
		$startcol2 = (NoteEntryPeer::NUM_COLUMNS - NoteEntryPeer::NUM_LAZY_LOAD_COLUMNS);

		EmployeePeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (EmployeePeer::NUM_COLUMNS - EmployeePeer::NUM_LAZY_LOAD_COLUMNS);

		ClientPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (ClientPeer::NUM_COLUMNS - ClientPeer::NUM_LAZY_LOAD_COLUMNS);

		ClientServicePeer::addSelectColumns($c);
		$startcol5 = $startcol4 + (ClientServicePeer::NUM_COLUMNS - ClientServicePeer::NUM_LAZY_LOAD_COLUMNS);

		OfficePeer::addSelectColumns($c);
		$startcol6 = $startcol5 + (OfficePeer::NUM_COLUMNS - OfficePeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(NoteEntryPeer::EMPLOYEE_ID,), array(EmployeePeer::ID,), $join_behavior);
				$c->addJoin(array(NoteEntryPeer::CLIENT_ID,), array(ClientPeer::ID,), $join_behavior);
				$c->addJoin(array(NoteEntryPeer::CLIENT_SERVICE_ID,), array(ClientServicePeer::ID,), $join_behavior);
				$c->addJoin(array(NoteEntryPeer::OFFICE_ID,), array(OfficePeer::ID,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = NoteEntryPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = NoteEntryPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = NoteEntryPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				NoteEntryPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined Employee rows

				$key2 = EmployeePeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = EmployeePeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = EmployeePeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					EmployeePeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (NoteEntry) to the collection in $obj2 (Employee)
				$obj2->addNoteEntry($obj1);

			} // if joined row is not null

				// Add objects for joined Client rows

				$key3 = ClientPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = ClientPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$omClass = ClientPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					ClientPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (NoteEntry) to the collection in $obj3 (Client)
				$obj3->addNoteEntry($obj1);

			} // if joined row is not null

				// Add objects for joined ClientService rows

				$key4 = ClientServicePeer::getPrimaryKeyHashFromRow($row, $startcol4);
				if ($key4 !== null) {
					$obj4 = ClientServicePeer::getInstanceFromPool($key4);
					if (!$obj4) {
	
						$omClass = ClientServicePeer::getOMClass($row, $startcol4);


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					ClientServicePeer::addInstanceToPool($obj4, $key4);
				} // if $obj4 already loaded

				// Add the $obj1 (NoteEntry) to the collection in $obj4 (ClientService)
				$obj4->addNoteEntry($obj1);

			} // if joined row is not null

				// Add objects for joined Office rows

				$key5 = OfficePeer::getPrimaryKeyHashFromRow($row, $startcol5);
				if ($key5 !== null) {
					$obj5 = OfficePeer::getInstanceFromPool($key5);
					if (!$obj5) {
	
						$omClass = OfficePeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj5 = new $cls();
					$obj5->hydrate($row, $startcol5);
					OfficePeer::addInstanceToPool($obj5, $key5);
				} // if $obj5 already loaded

				// Add the $obj1 (NoteEntry) to the collection in $obj5 (Office)
				$obj5->addNoteEntry($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


  static public function getUniqueColumnNames()
  {
    return array();
  }
	/**
	 * Returns the TableMap related to this peer.
	 * This method is not needed for general use but a specific application could have a need.
	 * @return     TableMap
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function getTableMap()
	{
		return Propel::getDatabaseMap(self::DATABASE_NAME)->getTable(self::TABLE_NAME);
	}

	/**
	 * The class that the Peer will make instances of.
	 *
	 * This uses a dot-path notation which is tranalted into a path
	 * relative to a location on the PHP include_path.
	 * (e.g. path.to.MyClass -> 'path/to/MyClass.php')
	 *
	 * @return     string path.to.ClassName
	 */
	public static function getOMClass()
	{
		return NoteEntryPeer::CLASS_DEFAULT;
	}

	/**
	 * Method perform an INSERT on the database, given a NoteEntry or Criteria object.
	 *
	 * @param      mixed $values Criteria or NoteEntry object containing data that is used to create the INSERT statement.
	 * @param      PropelPDO $con the PropelPDO connection to use
	 * @return     mixed The new primary key.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doInsert($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseNoteEntryPeer:doInsert:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseNoteEntryPeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(NoteEntryPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity
		} else {
			$criteria = $values->buildCriteria(); // build Criteria from NoteEntry object
		}

		if ($criteria->containsKey(NoteEntryPeer::ID) && $criteria->keyContainsValue(NoteEntryPeer::ID) ) {
			throw new PropelException('Cannot insert a value for auto-increment primary key ('.NoteEntryPeer::ID.')');
		}


		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		try {
			// use transaction because $criteria could contain info
			// for more than one table (I guess, conceivably)
			$con->beginTransaction();
			$pk = BasePeer::doInsert($criteria, $con);
			$con->commit();
		} catch(PropelException $e) {
			$con->rollBack();
			throw $e;
		}

		
    foreach (sfMixer::getCallables('BaseNoteEntryPeer:doInsert:post') as $callable)
    {
      call_user_func($callable, 'BaseNoteEntryPeer', $values, $con, $pk);
    }

    return $pk;
	}

	/**
	 * Method perform an UPDATE on the database, given a NoteEntry or Criteria object.
	 *
	 * @param      mixed $values Criteria or NoteEntry object containing data that is used to create the UPDATE statement.
	 * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doUpdate($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseNoteEntryPeer:doUpdate:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseNoteEntryPeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(NoteEntryPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$selectCriteria = new Criteria(self::DATABASE_NAME);

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity

			$comparison = $criteria->getComparison(NoteEntryPeer::ID);
			$selectCriteria->add(NoteEntryPeer::ID, $criteria->remove(NoteEntryPeer::ID), $comparison);

		} else { // $values is NoteEntry object
			$criteria = $values->buildCriteria(); // gets full criteria
			$selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
		}

		// set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$ret = BasePeer::doUpdate($selectCriteria, $criteria, $con);
	

    foreach (sfMixer::getCallables('BaseNoteEntryPeer:doUpdate:post') as $callable)
    {
      call_user_func($callable, 'BaseNoteEntryPeer', $values, $con, $ret);
    }

    return $ret;
  }

	/**
	 * Method to DELETE all rows from the note_entry table.
	 *
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	public static function doDeleteAll($con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(NoteEntryPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		$affectedRows = 0; // initialize var to track total num of affected rows
		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += NoteEntryPeer::doOnDeleteCascade(new Criteria(NoteEntryPeer::DATABASE_NAME), $con);
			$affectedRows += BasePeer::doDeleteAll(NoteEntryPeer::TABLE_NAME, $con);
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Method perform a DELETE on the database, given a NoteEntry or Criteria object OR a primary key value.
	 *
	 * @param      mixed $values Criteria or NoteEntry object or primary key or array of primary keys
	 *              which is used to create the DELETE statement
	 * @param      PropelPDO $con the connection to use
	 * @return     int 	The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
	 *				if supported by native driver or if emulated using Propel.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	 public static function doDelete($values, PropelPDO $con = null)
	 {
		if ($con === null) {
			$con = Propel::getConnection(NoteEntryPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			// invalidate the cache for all objects of this type, since we have no
			// way of knowing (without running a query) what objects should be invalidated
			// from the cache based on this Criteria.
			NoteEntryPeer::clearInstancePool();

			// rename for clarity
			$criteria = clone $values;
		} elseif ($values instanceof NoteEntry) {
			// invalidate the cache for this single object
			NoteEntryPeer::removeInstanceFromPool($values);
			// create criteria based on pk values
			$criteria = $values->buildPkeyCriteria();
		} else {
			// it must be the primary key



			$criteria = new Criteria(self::DATABASE_NAME);
			$criteria->add(NoteEntryPeer::ID, (array) $values, Criteria::IN);

			foreach ((array) $values as $singleval) {
				// we can invalidate the cache for this single object
				NoteEntryPeer::removeInstanceFromPool($singleval);
			}
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$affectedRows = 0; // initialize var to track total num of affected rows

		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += NoteEntryPeer::doOnDeleteCascade($criteria, $con);
			
				// Because this db requires some delete cascade/set null emulation, we have to
				// clear the cached instance *after* the emulation has happened (since
				// instances get re-added by the select statement contained therein).
				if ($values instanceof Criteria) {
					NoteEntryPeer::clearInstancePool();
				} else { // it's a PK or object
					NoteEntryPeer::removeInstanceFromPool($values);
				}
			
			$affectedRows += BasePeer::doDelete($criteria, $con);

			// invalidate objects in NoteEntryKidsPeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
			NoteEntryKidsPeer::clearInstancePool();

			// invalidate objects in EntryConcernPeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
			EntryConcernPeer::clearInstancePool();

			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * This is a method for emulating ON DELETE CASCADE for DBs that don't support this
	 * feature (like MySQL or SQLite).
	 *
	 * This method is not very speedy because it must perform a query first to get
	 * the implicated records and then perform the deletes by calling those Peer classes.
	 *
	 * This method should be used within a transaction if possible.
	 *
	 * @param      Criteria $criteria
	 * @param      PropelPDO $con
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	protected static function doOnDeleteCascade(Criteria $criteria, PropelPDO $con)
	{
		// initialize var to track total num of affected rows
		$affectedRows = 0;

		// first find the objects that are implicated by the $criteria
		$objects = NoteEntryPeer::doSelect($criteria, $con);
		foreach ($objects as $obj) {


			// delete related NoteEntryKids objects
			$c = new Criteria(NoteEntryKidsPeer::DATABASE_NAME);
			
			$c->add(NoteEntryKidsPeer::NOTE_ENTRY_ID, $obj->getId());
			$affectedRows += NoteEntryKidsPeer::doDelete($c, $con);

			// delete related EntryConcern objects
			$c = new Criteria(EntryConcernPeer::DATABASE_NAME);
			
			$c->add(EntryConcernPeer::NOTE_ENTRY_ID, $obj->getId());
			$affectedRows += EntryConcernPeer::doDelete($c, $con);
		}
		return $affectedRows;
	}

	/**
	 * Validates all modified columns of given NoteEntry object.
	 * If parameter $columns is either a single column name or an array of column names
	 * than only those columns are validated.
	 *
	 * NOTICE: This does not apply to primary or foreign keys for now.
	 *
	 * @param      NoteEntry $obj The object to validate.
	 * @param      mixed $cols Column name or array of column names.
	 *
	 * @return     mixed TRUE if all columns are valid or the error message of the first invalid column.
	 */
	public static function doValidate(NoteEntry $obj, $cols = null)
	{
		$columns = array();

		if ($cols) {
			$dbMap = Propel::getDatabaseMap(NoteEntryPeer::DATABASE_NAME);
			$tableMap = $dbMap->getTable(NoteEntryPeer::TABLE_NAME);

			if (! is_array($cols)) {
				$cols = array($cols);
			}

			foreach ($cols as $colName) {
				if ($tableMap->containsColumn($colName)) {
					$get = 'get' . $tableMap->getColumn($colName)->getPhpName();
					$columns[$colName] = $obj->$get();
				}
			}
		} else {

		}

		$res =  BasePeer::doValidate(NoteEntryPeer::DATABASE_NAME, NoteEntryPeer::TABLE_NAME, $columns);
    if ($res !== true) {
        foreach ($res as $failed) {
            $col = NoteEntryPeer::translateFieldname($failed->getColumn(), BasePeer::TYPE_COLNAME, BasePeer::TYPE_PHPNAME);
        }
    }

    return $res;
	}

	/**
	 * Retrieve a single object by pkey.
	 *
	 * @param      int $pk the primary key.
	 * @param      PropelPDO $con the connection to use
	 * @return     NoteEntry
	 */
	public static function retrieveByPK($pk, PropelPDO $con = null)
	{

		if (null !== ($obj = NoteEntryPeer::getInstanceFromPool((string) $pk))) {
			return $obj;
		}

		if ($con === null) {
			$con = Propel::getConnection(NoteEntryPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria = new Criteria(NoteEntryPeer::DATABASE_NAME);
		$criteria->add(NoteEntryPeer::ID, $pk);

		$v = NoteEntryPeer::doSelect($criteria, $con);

		return !empty($v) > 0 ? $v[0] : null;
	}

	/**
	 * Retrieve multiple objects by pkey.
	 *
	 * @param      array $pks List of primary keys
	 * @param      PropelPDO $con the connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function retrieveByPKs($pks, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(NoteEntryPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$objs = null;
		if (empty($pks)) {
			$objs = array();
		} else {
			$criteria = new Criteria(NoteEntryPeer::DATABASE_NAME);
			$criteria->add(NoteEntryPeer::ID, $pks, Criteria::IN);
			$objs = NoteEntryPeer::doSelect($criteria, $con);
		}
		return $objs;
	}

} // BaseNoteEntryPeer

// This is the static code needed to register the MapBuilder for this table with the main Propel class.
//
// NOTE: This static code cannot call methods on the NoteEntryPeer class, because it is not defined yet.
// If you need to use overridden methods, you can add this code to the bottom of the NoteEntryPeer class:
//
// Propel::getDatabaseMap(NoteEntryPeer::DATABASE_NAME)->addTableBuilder(NoteEntryPeer::TABLE_NAME, NoteEntryPeer::getMapBuilder());
//
// Doing so will effectively overwrite the registration below.

Propel::getDatabaseMap(BaseNoteEntryPeer::DATABASE_NAME)->addTableBuilder(BaseNoteEntryPeer::TABLE_NAME, BaseNoteEntryPeer::getMapBuilder());

