generator:
  class: sfPropelGenerator
  param:
    model_class:           Frequency
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          frequency
    with_propel_route:     1
    css:                    false
    
    config:
      actions: ~
      fields:  ~
      list:
        sort:  [sort_order, asc]
        title: Frequency List
        display: [=name, weekly_hours, description, sort_order]
        object_actions:
          _edit: ~
      filter:
        class: false
      form:    ~
      edit:    ~
      new:     ~
