<?php


/**
 * Skeleton subclass for representing a row from one of the subclasses of the 'client_service' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Thu Sep 10 16:36:23 2009
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class SchoolAge extends ClientService {

	/**
	 * Constructs a new SchoolAge class, setting the object_type column to ClientServicePeer::CLASSKEY_SCHOOL_AGE.
	 */
	public function __construct()
	{
		parent::__construct();
		$this->setObjectType(ClientServicePeer::CLASSKEY_SCHOOL_AGE);
	}

} // SchoolAge
