sedcarReportSuccess:
  stylesheets:    [-*, print.css {media: print}]
  layout: print
  
arqReportSuccess:
  stylesheets:    [-*, print.css {media: print}]
  layout: print

crqReportSuccess:
  stylesheets:    [-*, print.css {media: print}, reports/crq.css]
  layout: print
  
coreEvalReportSuccess:
  javascripts: [tableActions.min.js]