generator:
  class: sfPropelGenerator
  param:
    model_class:           Service
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          service
    with_propel_route:     1
    css:                   false

    config:
      actions: ~
      fields:  ~
      list:
        title: Services List
        display: [=name, id]
        object_actions:
          _edit: ~
      filter:
        class: false
      form:    ~
      edit:    ~
      new:     ~
